Translate React website Home page
reactjs/pt-br.react.dev pull request #655
Opened 2023-04-22 03:53 UTC by jhonmike

### pt-br
Após a publicação do novo site, algumas das páginas que já tínhamos traduzido da versão beta se perderam porque a oficial mudou totalmente, uma delas foi a página inicial do site, nesse PR se encontra a nova tradução da mesma.
### en
After the publication of the new site, some of the pages that we had already translated from the beta version were lost because the official one was completely changed, one of them was the homepage of the site, in this PR is the new translation of the same

2023-04-25 06:02 UTC, VitorGultzgoff commented on src/components/Layout/HomeContent.js
> +              combine-os em telas interas, páginas, e aplicativos.
Acredito que aqui seria `em telas inteiras`, correto?

2023-04-25 06:10 UTC, VitorGultzgoff commented on src/components/Layout/HomeContent.js
> +              conteúdos condicionalmente? Use uma instrução <Code>if</Code>.
O que você acha de alterar de `Use uma instrução` para `Utilize`/`Use`?
```suggestion
              conteúdos condicionalmente? Utilize <Code>if</Code>.
```

Não sei se há a necessidade de referenciar `instrução`.

2023-04-25 06:20 UTC, VitorGultzgoff commented on src/components/Layout/HomeContent.js
> +              Vá full-stack <br className="hidden lg:inline" />
`Vá full-stack` é uma tradução direta que me parece meio errada, porque o `Go full-stack` é no sentido de transformar/desfrutar/utilizar de uma estrutura full-stack com framework.

Porém infelizmente não tenho uma sugestão neste momento, se alguém tiver uma ideia de uma alternativa.

2023-04-25 06:22 UTC, VitorGultzgoff commented on src/components/Layout/HomeContent.js
> +                Comece com um framework
Uma alternativa, mas não me importo tanto, seria:
```suggestion
                Inicie com um framework
```

2023-04-25 06:27 UTC, VitorGultzgoff commented on src/components/Layout/HomeContent.js
> +                          permitem que você crie aplicativos em React para
Acredito que aqui seria `permite` porque está se referenciando ao `Expo` ao invés de `As pessoas`.
```suggestion
                          permite que você crie aplicativos em React para
```

2023-04-25 06:30 UTC, VitorGultzgoff commented on src/components/Layout/HomeContent.js
> +                plataforma e formar equipes que possuem recursos inteiros de
O que acha de:

```suggestion
                plataforma e formar equipes que possuem funcionalidades de
```

2023-04-25 06:36 UTC, VitorGultzgoff commented on src/components/Layout/HomeContent.js
> +    alt: 'Sunil Pai falando no React Índia',
Acredito que não há necessidade do acento quando se trata do **nome do evento**.
```suggestion
    alt: 'Sunil Pai falando no React India',
```

2023-04-25 06:37 UTC, VitorGultzgoff commented on src/components/Layout/HomeContent.js
> +            title: 'Palestrar React 18',
```suggestion
            title: 'Palestra React 18',
```

2023-04-25 06:44 UTC, VitorGultzgoff reviewed
Algumas sugestões/confirmações, trabalho fenomenal! 🚀

2023-04-25 14:41 UTC, limagb commented on src/components/Layout/HomeContent.js
> +            <Header>Crie interfaces de usuários a partir de componentes</Header>
Poderia ser "Crie interfaces de usuário a partir..." ("usuário" no singular mesmo) no lugar de "Crie interfaces de usuários a partir..."?

2023-04-26 10:48 UTC, jhonmike commented on src/components/Layout/HomeContent.js
> +              Vá full-stack <br className="hidden lg:inline" />
Talvez não traduzir essa parte? `Go` é um termo comum entre brasileiros, hahaha ou `Bora full-stack` 😂

2023-04-26 10:57 UTC, jhonmike commented on src/components/Layout/HomeContent.js
> +              Vá full-stack <br className="hidden lg:inline" />
Vou deixar apenas ` Full-stack com um framework` já da para entender o contexto IMHO

2023-04-26 19:38 UTC, jussarasoares submitted a review, later dismissed

2023-04-27 01:30 UTC, natrodrigo commented on src/components/Layout/HomeContent.js
> +              Vá full-stack <br className="hidden lg:inline" />
@jhonmike sugiro

"Torne full stack com um framework"

Full stack no português não tem hífen pelo que pesquisei.

2023-04-27 01:53 UTC, natrodrigo requested changes
@jhonmike, obrigado pela contribuição! Está muito bom. 
Deixei alguns comentários para sua análise.

2023-04-27 01:53 UTC, natrodrigo commented on src/components/Layout/HomeContent.js
> +              API Referência
```suggestion
              Referência das APIs
```

O texto é meio grande para o botão, mas acho que seria mais adequado. Será que fica ruim no mobile?

2023-04-27 01:53 UTC, natrodrigo commented on src/components/Layout/HomeContent.js
> +              desenvolvedores, usar o React parece o mesmo. Ele foi projetado
```suggestion
              desenvolvedores, é possível usar o React da mesma maneira. Ele foi projetado
```

O texto assim fica mais longo, mas o termo `feels the same` é quase uma gíria sem um equivalente em português. Acho que o ideal é reformular para uma linguagem mais amigável para o português.

2023-04-27 01:53 UTC, natrodrigo commented on src/components/Layout/HomeContent.js
> +              Essa sintaxe de marcação é chamada de JSX. É uma extensão de
```suggestion
              Essa sintaxe de tags é chamada de JSX. É uma extensão de
```

O termo `markup` não tem uma tradução em português. No PR #660 traduzi ele como `tag` e na maioria dos casos pareceu bom.
Minha sugestão é usar ele para manter uma uniformidade.

2023-04-27 01:53 UTC, natrodrigo commented on src/components/Layout/HomeContent.js
> +              sintaxe JavaScript popularizada pelo React. Colocar a marcação JSX
```suggestion
              sintaxe JavaScript popularizada pelo React. Colocar tags JSX
```

O termo `markup` não tem uma tradução em português. No PR #660 traduzi ele como `tag` e na maioria dos casos pareceu bom.
Minha sugestão é usar ele para manter uma uniformidade.

2023-04-27 01:53 UTC, natrodrigo commented on src/components/Layout/HomeContent.js
> +              próxima à lógica de renderização relacionada torna os componentes
```suggestion
              em conjunto com a lógica de renderização relacionada torna os componentes
```

Acho que essas palavras se encaixam melhor para o português. O termo `close` em inglês têm uma abrangência maior de significados e se encaixa melhor em diferentes contextos do que o termo `próxima` do português.

2023-04-27 01:53 UTC, natrodrigo commented on src/components/Layout/HomeContent.js
> +              framework React full-stack como{' '}
```suggestion
              framework React full stack como{' '}
```

Vejo o termo full stack ser usado no português sem hífen em todas as situações. Acredito que é o mais correto.

2023-04-27 01:53 UTC, natrodrigo commented on src/components/Layout/HomeContent.js
> +                Sua equipe pode enviar para várias plataformas sem sacrificar a
```suggestion
                Sua equipe pode fazer deploy para várias plataformas sem sacrificar a
```

Apesar de fugir um pouco do original, acho que esse termo é mais popular na comunidade e seria melhor entendido por leitores brasileiros neste contexto.

2023-04-27 02:01 UTC, jhonmike commented on src/components/Layout/HomeContent.js
> +              API Referência
Vou testar

2023-04-27 02:09 UTC, merged