docs(pt-br): translate writing-markup-with-jsx page
reactjs/pt-br.react.dev pull request #657
Opened 2023-04-24 17:13 UTC by volinha

2023-04-25 02:55 UTC, jhonmike commented
@volinha é importante vc avisar nessa [issue](https://github.com/reactjs/pt-br.react.dev/issues/555) qual pagina vc vai traduzir, para que outras pessoas não comecem traduzir a mesma

2023-04-27 01:17 UTC, natrodrigo requested changes
@volinha , obrigado por sua contribuição, parabéns!

Deixei alguns apontamentos para você analisar.

2023-04-27 01:17 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +Mas à medida que a Web se tornava mais interativa, a lógica determinava cada vez mais o conteúdo. O JavaScript ficou a cargo do HTML! É por isso que **no React, a lógica de renderização e a marcação
```suggestion
Mas à medida que a Web se tornava mais interativa, a lógica determinava cada vez mais o conteúdo. O JavaScript se tornou responsável por criar o HTML! É por isso que **no React, a lógica de renderização e a marcação vivem juntas no mesmo lugar — os componentes.**
```

Sugiro esta modificação porque o original dá um sentido dúbio de que o HTML agora é responsável pelo JS, quando na verdade é o contrário.

2023-04-27 01:17 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +<Diagram name="writing_jsx_form" height={330} width={325} alt="Componente React com HTML e JavaScript de exemplos anteriores misturados. O nome da função é Form contendo dois manipuladores onClick e
```suggestion
<Diagram name="writing_jsx_form" height={330} width={325} alt="Componente React com HTML e JavaScript de exemplos anteriores misturados. O nome da função é Form contendo duas funções onClick e onSubmit destacados em amarelo. Após as funções, está o HTML destacado em roxo. O HTML contém um elemento de form com um elemento input aninhado, cada um com uma propriedade onClick.">
```

Sugiro funções para ficar em conformidade e por essa palavra se encaixar melhor no contexto.
Sugiro que a indicação das tags utilizadas não sejam traduzidas.

2023-04-27 01:17 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +Manter a lógica de renderização e a marcação de um botão juntas garante que eles permaneçam sincronizados entre si em todas as edições. Por outro lado, os detalhes não relacionados, como a marcação d
```suggestion
Manter a lógica de renderização e as tags de um botão juntas garante que elas permaneçam sincronizadas entre si em todas as edições. Por outro lado, os detalhes não relacionados, como as tags do botão e as tags da barra lateral, são isolados uns dos outros, tornando mais seguro alterar qualquer um deles por conta própria.
```

2023-04-27 01:17 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +Cada componente do React é uma função JavaScript que pode conter alguma marcação que o React renderiza no navegador. Os componentes do React usam uma extensão de sintaxe chamada JSX para representar
```suggestion
Cada componente React é uma função JavaScript que pode conter tags que o React renderiza no navegador. Componentes React utilizam uma extensão de sintaxe chamada JSX para representar essas tags. JSX parece muito com HTML, mas é um pouco mais rígido e pode exibir informações de forma dinâmica.
```

Sugiro esta tradução para ficar em conformidade com o texto traduzido na PR #660

2023-04-27 01:17 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +## Convertendo HTML em JSX {/*converting-html-to-jsx*/}
```suggestion
## Convertendo HTML para JSX {/*converting-html-to-jsx*/}
```

2023-04-27 01:17 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +Isso ocorre porque o JSX é mais rígido e possui algumas regras a mais que o HTML! Se você ler as mensagens de erro acima, elas o guiarão para corrigir a marcação ou você poderá seguir o guia abaixo.
```suggestion
Isso ocorre porque o JSX é mais rígido e possui algumas regras a mais que o HTML! Se você ler as mensagens de erro acima, elas o guiarão para corrigir as tags ou você poderá seguir o guia abaixo.
```

2023-04-27 01:17 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +Você pode [encontrar todos esses atributos na lista de propriedades do componente DOM.](/reference/react-dom/components/common) Se você errar, não se preocupe — o React imprimirá uma mensagem com uma
```suggestion
Você pode [encontrar todos esses atributos na lista de propriedades do componente DOM.](/reference/react-dom/components/common) Se você fizer algo de errado, não se preocupe — o React imprimirá uma mensagem com uma possível correção para o [console do navegador.](https://developer.mozilla.org/docs/Tools/Browser_Console)
```

2023-04-27 01:17 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +* Os componentes do React agrupam a lógica de renderização junto com a marcação porque estão relacionados.
```suggestion
* Os componentes do React agrupam a lógica de renderização junto com as tags porque estão relacionados.
```

Sugiro a palavra `tag` para tradução de `markup` em coerência com #660

2023-04-27 01:17 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +* As mensagens de erro geralmente indicam a direção certa para corrigir sua marcação.
```suggestion
* As mensagens de erro geralmente indicam a direção certa para corrigir suas tags.
```

Sugiro a palavra `tag` para tradução de `markup` em coerência com #660

2023-04-28 03:53 UTC, natrodrigo requested changes
Adicionei mais uma review pois nas diretrizes não devemos traduzir nomes de classes, variáveis, etc. Adicionei alguns comentários para facilitar o commit. Obrigado!

2023-04-28 03:53 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +    class="foto"
```suggestion
    class="photo"
```

Pelas diretrizes, não devemos traduzir nomes de variáveis, classes, etc. No máximo comentários ou textos se for pertinente

2023-04-28 03:53 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +    class="foto"
```suggestion
    class="photo"
```

2023-04-28 03:53 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +  className="foto"
```suggestion
  className="photo"
```

2023-04-28 03:53 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +        className="foto"
```suggestion
        className="photo" 
```

2023-04-28 03:53 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +export default function ListaDeTarefas() {
```suggestion
export default function TodoList() {
```

2023-04-28 03:53 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +    <p class="resumo">
```suggestion
    <p class="summary">
```

2023-04-28 03:53 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +.resumo {
```suggestion
.summary{
```

2023-04-28 03:53 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +      <p className="resumo">
```suggestion
      <p className="summary">
```

2023-04-28 03:53 UTC, natrodrigo commented on src/content/learn/writing-markup-with-jsx.md
> +.resumo {
```suggestion
.summary {
```

2025-01-31 12:26 UTC, GabeHenrique approved these changes

2026-06-16 02:08 UTC, jhonmike commented
Olá @volinha, muito obrigado pela contribuição! 🙏

Esta página já foi traduzida e mergeada em #1014, então vou fechar este PR para manter o backlog organizado.

Sua ajuda é muito bem-vinda — se quiser pegar uma página que ainda está pendente, a issue #555 mantém a lista atualizada do que falta traduzir. Valeu! 🚀

2026-06-16 02:08 UTC, closed without merging