Translate add-react-to-an-existing-project
reactjs/pt-br.react.dev pull request #659
Opened 2023-04-25 04:17 UTC by revogabe

In this PR I am translating the page that I was designated called "add-react-to-an-existing-project" I also saw that in the open issue this page is described with the old name.

2023-04-25 13:54 UTC, lirbre commented on src/content/learn/add-react-to-an-existing-project.md
> +Se você quer adicionar alguma interatividade ao seu projeto existente, você não precisa reescrevê-lo em React. Adicione React à sua pilha existente e renderize componentes React interativos em qualqu
A tradução de `stack` pra `pilha` acaba não fazendo muito sentido, também achei a sintaxe da segunda frase levemente confusa. 

Sugestão: 

Se você quer adicionar alguma interatividade ao seu projeto existente, você não precisa reescrevê-lo em React. Adicione React à sua aplicação e renderize componentes interativos em qualquer lugar utilizando React.

2023-04-25 15:49 UTC, revogabe commented on src/content/learn/add-react-to-an-existing-project.md
> +Se você quer adicionar alguma interatividade ao seu projeto existente, você não precisa reescrevê-lo em React. Adicione React à sua pilha existente e renderize componentes React interativos em qualqu
Obrigado irei dar uma olhada novamente na tradução

2023-04-25 15:56 UTC, uilian commented on src/content/learn/add-react-to-an-existing-project.md
> +Muitos frameworks baseados em React são full-stack e permitem que seu aplicativo React aproveite o servidor. No entanto, você pode usar a mesma abordagem mesmo se não puder ou não quiser executar Jav
```suggestion
Muitos frameworks baseados em React são full-stack e permitem que seu aplicativo React tire proveito dos recursos do servidor. No entanto, você pode usar a mesma abordagem mesmo se não puder ou não quiser executar JavaScript no servidor. Nesse caso, exponha os HTML/CSS/JS exportados ([saída `next export`](https://nextjs.org/docs/advanced-features/static-html-export) para o Next.js, padrão para o Gatsby) em `/some-app/` em vez disso.
```

2023-04-25 15:56 UTC, uilian commented on src/content/learn/add-react-to-an-existing-project.md
> +Em vez disso, você provavelmente deseja renderizar seus componentes React em lugares específicos em seu HTML. Abra sua página HTML (ou os modelos do servidor que a geram) e adicione um atributo único
```suggestion
Em vez disso, você provavelmente deseja renderizar seus componentes React em lugares específicos em seu HTML. Abra sua página HTML (ou os modelos do servidor que a geram) e adicione um identificador único [`id`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id) a qualquer tag, por exemplo:
```

2023-04-26 02:42 UTC, revogabe commented on src/content/learn/add-react-to-an-existing-project.md
> +Muitos frameworks baseados em React são full-stack e permitem que seu aplicativo React aproveite o servidor. No entanto, você pode usar a mesma abordagem mesmo se não puder ou não quiser executar Jav
Done! ✍️

2023-04-27 02:21 UTC, natrodrigo requested changes
@revogabe obrigado pela contribuição. A tradução está ótima!

2023-04-27 02:21 UTC, natrodrigo commented on src/content/learn/add-react-to-an-existing-project.md
> +Muitos frameworks baseados em React são full-stack e permitem que seu aplicativo React tire proveito do servidor. No entanto, você pode usar a mesma abordagem mesmo se não puder ou não quiser executa
```suggestion
Muitos frameworks baseados em React são full stack e permitem que seu aplicativo React tire proveito do servidor. No entanto, você pode usar a mesma abordagem mesmo se não puder ou não quiser executar JavaScript no servidor. Nesse caso, exponha os HTML/CSS/JS exportados ([saída `next export`](https://nextjs.org/docs/advanced-features/static-html-export) para o Next.js, padrão para o Gatsby) em `/some-app/` em vez disso.
```
Full stack é usado no português sem hífen.

2023-04-27 02:30 UTC, jhonmike commented on src/content/learn/add-react-to-an-existing-project.md
> +[React Native](https://reactnative.dev/) também pode ser integrado incrementalmente em aplicativos nativos existentes. Se você possui um aplicativo nativo existente para Android (Java ou Kotlin) ou i
```suggestion
[React Native](https://reactnative.dev/) também pode ser integrado incrementalmente em aplicativos nativos existentes. Se você possui um aplicativo nativo existente para Android (Java ou Kotlin) ou iOS (Objective-C ou Swift), [siga este guia](https://reactnative.dev/docs/integration-with-existing-apps) para adicionar uma tela React Native a ele.
```

2023-04-27 02:31 UTC, jhonmike commented
Tenta rodar local para ver porque o build esta quebrando

2023-04-27 03:58 UTC, revogabe commented
Done! 🥳

2023-04-27 12:05 UTC, jhonmike commented on src/content/learn/add-react-to-an-existing-project.md
> +Se você quer adicionar alguma interatividade ao seu projeto existente, você não precisa reescrevê-lo em React. Adicione React à sua pilha existente e renderize componentes React interativos em qualqu
eu usuária stack mesmo 🤔

2023-04-27 12:20 UTC, felipefreitag commented on src/content/learn/add-react-to-an-existing-project.md
> +**Você precisa instalar o [Node.js](https://nodejs.org/en/) para o desenvolvimento local.** Embora você possa [experimentar o React](/learn/installation#try-react) online ou com uma simples página HT
"requer" está concordando com "a maioria", está ok

2023-04-27 12:27 UTC, felipefreitag commented on src/content/learn/add-react-to-an-existing-project.md
> +Se todo o conteúdo da sua página foi substituído por um "Hello World!", tudo funcionou! Continue lendo.
```suggestion
Se todo o conteúdo da sua página foi substituído por um "Hello, world!", tudo funcionou! Continue lendo.
```
Aqui se trata do texto literal no código da linha 78

2023-04-27 12:35 UTC, felipefreitag commented on src/content/learn/add-react-to-an-existing-project.md
> +Observe como o conteúdo HTML original de index.html é preservado, mas o seu próprio componente React NavigationBar agora aparece dentro do <nav id="navigation" /> do seu HTML. Leia a documentação de
```suggestion
Observe como o conteúdo HTML original de `index.html` é preservado, mas o seu próprio componente React `NavigationBar` agora aparece dentro do `<nav id="navigation" />` do seu HTML. Leia a documentação de uso de [`createRoot` usage documentation](/reference/react-dom/client/createRoot#rendering-a-page-partially-built-with-react) para aprender mais sobre como renderizar componentes React dentro de uma página HTML existente.
```
Suponho que os backticks devam ser mantidos?

2023-04-27 12:36 UTC, felipefreitag commented on src/content/learn/add-react-to-an-existing-project.md
> +Quando você adota o React em um projeto existente, é comum começar com pequenos componentes interativos (como botões) e, gradualmente, "subir de nível" até que eventualmente toda a sua página seja co
```suggestion
Quando você adota o React em um projeto existente, é comum começar com pequenos componentes interativos (como botões) e, gradualmente, "subir de nível" até que eventualmente toda a sua página seja construída com React. Se você chegar a esse ponto, recomendamos migrar para [um framework React](/learn/start-a-new-react-project) imediatamente para aproveitar ao máximo o React.
```

2023-04-27 12:37 UTC, felipefreitag commented on src/content/learn/add-react-to-an-existing-project.md
> +## Usando o React Native em um aplicativo móvel nativo existente. {/*using-react-native-in-an-existing-native-mobile-app*/}
```suggestion
## Usando o React Native em um aplicativo móvel nativo existente {/*using-react-native-in-an-existing-native-mobile-app*/}
```
O original não tem pontuação no final da frase

2023-04-27 16:38 UTC, revogabe commented
Done ! 🥳

2023-04-27 18:52 UTC, felipefreitag commented on src/content/learn/add-react-to-an-existing-project.md
> +**Você precisa instalar o [Node.js](https://nodejs.org/en/) para o desenvolvimento local.** Embora você possa [experimentar o React](/learn/installation#try-react) online ou com uma simples página HT
```suggestion
**Você precisa instalar o [Node.js](https://nodejs.org/pt-br/) para o desenvolvimento local.** Embora você possa [experimentar o React](/learn/installation#try-react) online ou com uma simples página HTML, realisticamente a maioria das ferramentas JavaScript que você vai querer usar para desenvolvimento requer o Node.js.
```

2023-04-27 18:54 UTC, felipefreitag commented on src/content/learn/add-react-to-an-existing-project.md
> +1. **Configure um ambiente JavaScript** que permita o uso da sintaxe [JSX](/learn/writing-markup-with-jsx), divida o seu código em módulos com a sintaxe [`import`](https://developer.mozilla.org/en-US
```suggestion
1. **Configure um ambiente JavaScript** que permita o uso da sintaxe [JSX](/learn/writing-markup-with-jsx), divida o seu código em módulos com a sintaxe [`import`](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Statements/import) / [`export`](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Statements/export) e utilize pacotes (por exemplo, React) do registro de pacotes [npm](https://www.npmjs.com/).
```

2023-04-27 18:54 UTC, felipefreitag commented on src/content/learn/add-react-to-an-existing-project.md
> +**Você precisa instalar o [Node.js](https://nodejs.org/en/) para o desenvolvimento local.** Embora você possa [experimentar o React](/learn/installation#try-react) online ou com uma simples página HT
Acabei de ver que o glossário sugere usar links externos em pt-br quando existirem :)

2023-04-27 18:55 UTC, felipefreitag commented on src/content/learn/add-react-to-an-existing-project.md
> +Em vez disso, você provavelmente deseja renderizar seus componentes React em lugares específicos em seu HTML. Abra sua página HTML (ou os modelos do servidor que a geram) e adicione um identificador
```suggestion
Em vez disso, você provavelmente deseja renderizar seus componentes React em lugares específicos em seu HTML. Abra sua página HTML (ou os modelos do servidor que a geram) e adicione um identificador único [`id`](https://developer.mozilla.org/pt-BR/docs/Web/HTML/Global_attributes/id) a qualquer tag, por exemplo:
```

2023-04-27 19:02 UTC, revogabe commented
Obrigado não tinha me atentado a estes links, desculpe estar tendo que fazer bastante mudanças, mas estou bem feliz por estar contribuindo com a tradução! 😅

2023-04-27 22:31 UTC, jhonmike commented
>Obrigado não tinha me atentado a estes links, desculpe estar tendo que fazer bastante mudanças, mas estou bem feliz por estar contribuindo com a tradução! 😅
Rapaz tradução é assim mesmo, na real quando mais sugestões melhor fica a doc, ta showw!!

2023-04-28 02:31 UTC, jhonmike approved these changes

2023-04-28 02:34 UTC, merged

2023-04-28 02:46 UTC, revogabe commented
Tenkiu!! 🥳 Lets GO!!