Tradução da página `start-a-new-react-project.md`
reactjs/pt-br.react.dev pull request #662
Opened 2023-04-25 16:14 UTC by NivaldoFarias

### Links auxiliares

- [Página original](https://react.dev/learn/start-a-new-react-project)

2023-04-25 23:45 UTC, jotaRenan reviewed
Parabéns pela ótima tradução, Nivaldo! Deixei alguns comentários _minor_.

2023-04-25 23:45 UTC, jotaRenan commented on src/content/learn/start-a-new-react-project.md
> +title: Inicie um novo projeto em React
```suggestion
title: Inicie um Novo Projeto React
```

Creio que faça sentido mantermos o upper-casing do texto original. Um outro pequeno detalhe é que o original utiliza "React Project" sem preposição, de forma que "Projeto React" me parece mais fidedigno. O que você acha?

2023-04-25 23:45 UTC, jotaRenan commented on src/content/learn/start-a-new-react-project.md
> +**[Next.js](https://nextjs.org/) é um *framework* React *full-stack.*** É versátil e permite que você crie aplicações React de qualquer tamanho--desde um blog majoritariamente estático à uma aplicaçã
```suggestion
**[Next.js](https://nextjs.org/) é um *framework* React *full-stack.*** É versátil e permite que você crie aplicações React de qualquer tamanho--desde um blog majoritariamente estático a uma aplicação dinâmica e complexa. Para criar um novo projeto com Next.js, execute no seu terminal:
```

A maldita crase é dispensada caso seja seguida de um artigo ([fonte](http://www.nilc.icmc.usp.br/nilc/minigramatica/mini/acraseeosartigos.htm#:~:text=Isto%20%C3%A9%2C%20a%20crase%20%C3%A9,est%C3%A1%20acompanhada%20de%20um%20determinante.))

2023-04-25 23:45 UTC, jotaRenan commented on src/content/learn/start-a-new-react-project.md
> +Mesmo que você não precise de roteamento ou busca de dados no início, você provavelmente vai querer adicionar algumas bibliotecas para eles. Conforme seu pacote JavaScript cresce com cada nova funcio
```suggestion
Mesmo que você não precise de roteamento ou busca de dados no início, você provavelmente vai querer adicionar algumas bibliotecas para eles. Conforme seu pacote JavaScript cresce com cada nova funcionalidade, você talvez tenha que descobrir como dividir o código para cada rota individualmente. Conforme suas necessidades de busca de dados ficam mais complexas, é provável que vá encontrar cascatas de comunicação servidor-cliente que fazem sua aplicação parecer muito lenta. Conforme seu público passe a incluir mais usuários com condições de rede ruins e dispositivos de baixo desempenho, você pode precisar gerar HTML a partir de seus componentes para exibir conteúdo cedo--seja no servidor, ou durante o tempo de construção (*build*). Mudar sua configuração para executar parte do seu código no servidor ou durante a construção pode ser bem complicado.
```

2023-04-25 23:45 UTC, jotaRenan commented on src/content/learn/start-a-new-react-project.md
> +  // 1. Você está no servidor, então você pode se comunicar com sua camada de dados. Rotas de APIs não são necessárias.
legal, eu nao havia traduzido comentários na minha PR e farei isso agora que vi a sua!

2023-04-26 11:32 UTC, NivaldoFarias commented on src/content/learn/start-a-new-react-project.md
> +title: Inicie um Novo Projeto em React
@jotaRenan alterei pra manter as palavras capitalizadas, mas mantive a preposição. Ao meu ver soa mais semântico,

2023-04-27 05:53 UTC, devlulcas approved these changes
A tradução está bem feita e completamente correta pelo que eu li.

2023-04-27 12:10 UTC, jhonmike approved these changes

2023-04-27 12:14 UTC, merged

2023-04-27 12:22 UTC, natrodrigo requested changes
@NivaldoFarias , obrigado pela contribuição!
A tradução está muito boa, parabéns! Deixei apenas um apontamento para sua avaliação.

2023-04-27 12:22 UTC, natrodrigo commented on src/content/learn/start-a-new-react-project.md
> +Mesmo que você não precise de roteamento ou busca de dados no início, você provavelmente vai querer adicionar algumas bibliotecas para eles. Conforme seu pacote JavaScript cresce com cada nova funcio
```suggestion
Mesmo que você não precise de roteamento ou busca de dados em API no início, talvez você precise adicionar algumas bibliotecas para isso depois. Conforme seu pacote JavaScript cresce com cada nova funcionalidade, você talvez tenha que descobrir como dividir o código para cada rota individualmente. Conforme suas necessidades de busca de dados ficam mais complexas, é provável que vá encontrar cascatas de comunicação servidor-cliente que fazem sua aplicação parecer muito lenta. Conforme seu público passe a incluir mais usuários com condições de rede ruins e dispositivos de baixo desempenho, você pode precisar gerar HTML a partir de seus componentes para exibir conteúdo cedo--seja no servidor, ou durante o tempo de construção (*build*). Mudar sua configuração para executar parte do seu código no servidor ou durante a construção pode ser bem complicado.
```

Reformei a frase para ficar mais amigável no português, e achei interessante enfatizar que a 'busca de dados' é em uma API, que fica claro em inglês pela palavra `fetching`, mas esse verbo não existe no português.