Tradução das Sidebar
reactjs/pt-br.react.dev pull request #663
Opened 2023-04-25 21:50 UTC by emersonbroga

- SidebarHome
 - SidebarLearn
 - SidebarBlog
 - SidebarCommunity
 - SidebarReference

2023-04-26 03:13 UTC, jotaRenan reviewed
Oi Emerson, muito obrigado pela sua maravilhosa tradução nessa contribuição. 

Comentei algumas sugestões: a maioria envolve adequar letras maiúsculas para que sigam o estilo definido na documentação original. Em outros casos, sugeri manter nomes próprios do react em inglês. Houve apenas um caso em que havia um erro de digitação na tradução. Abç e vamos nessa!

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Estado: Memória de um componente",
```suggestion
          "title": "Estado: Memória de um Componente",
```

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Enfileirando uma série de atualizações de estado",
```suggestion
          "title": "Enfileirando uma Série de Atualizações de Estado",
```

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Atualizando objetos no estado",
```suggestion
          "title": "Atualizando Objetos no Estado",
```

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Atualizando matrizes no estado",
```suggestion
          "title": "Atualizando Vetores no Estado",
```

Quando vejo "arrays" sendo traduzido, geralmente é para "vetores", ao passo que "matrizes" geralmente são usadas para se referir a arrays N-dimensionais, com N > 1. O que você acha dessa alteração?

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Reagindo à entrada com estado",
```suggestion
          "title": "Reagindo à Entrada com Estado",
```

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Escolhendo a estrutura do estado",
```suggestion
          "title": "Escolhendo a Estrutura do Estado",
```

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Compartilhamento de estado entre componentes",
```suggestion
          "title": "Compartilhando Estado entre Componentes",
```

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Preservando e redefinindo o estado",
```suggestion
          "title": "Preservando e Redefinindo Estado",
```

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Extraindo a lógica de estado para um Reducer",
```suggestion
          "title": "Extraindo a Lógica de Estado para um Reducer",
```

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Escalabilidade vertical com redutor e contexto",
Emerson, por que voce preferiu incluir a palavra "vertical" nesse título? 
Na tradução atual, o termo `reducer` não é traduzido. Acho que faz sentido, e você? 
Já `Context` é traduzido - o que será que o resto da comunidade pensa sobre isso? Pra mim, é um conceito de react e, por isso, deveria manter o nome próprio sem tradução.

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Reutilizando lógica com hooks personalizados",
```suggestion
          "title": "Reutilizando Lógica com Hooks Personalizados",
```

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Removendo dependências de efeito",
```suggestion
          "title": "Removendo Dependências de Effects",
```

https://github.com/reactjs/pt-br.react.dev/issues/555#issuecomment-1522519263

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Separando Eventos de Efeitos",
```suggestion
          "title": "Separando Eventos de Effects",
```

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Ciclo de vida dos efeitos reativos",
```suggestion
          "title": "Ciclo de Vida dos Efeitos Reativos",
```

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Você pode não precisar de um efeito",
```suggestion
          "title": "Talvez Você Não Precise de um Effect",
```

Estou sugerindo essa tradução para que fique similar ao definido [nessa PR](https://github.com/reactjs/pt-br.react.dev/pull/664/files#diff-c51e8d36dfb293693cc83987186dbfce4c3a83a9407ec29b73173b810ea02f77R198)

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Sincronizando com Efeitos",
```suggestion
          "title": "Sincronizando com Effects",
```

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Valores de referência com Refs",
```suggestion
          "title": "Referenciando Valores Através de Refs",
```

Estou sugerindo essa tradução para que fique similar ao definido [nessa PR](https://github.com/reactjs/pt-br.react.dev/pull/664/files#diff-c51e8d36dfb293693cc83987186dbfce4c3a83a9407ec29b73173b810ea02f77R24)

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +      "title": "Escotilhas de escape",
```suggestion
      "title": "Saídas de Emergência",
```

Novamente, estou incerto sobre esse termo, e curioso para ver o consenso ao qual a comunidade chegará

2023-04-26 03:13 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Tutorial: Jogo-da-velha",
```suggestion
          "title": "Tutorial: Jogo-da-Velha",
```

2023-04-26 12:46 UTC, natrodrigo commented on src/sidebarLearn.json
> +          "title": "Atualizando matrizes no estado",
Eu sugiro a utilização da palavra 'Listas'. Vejo ela ser mais usada que vetores e matrizes.

2023-04-26 13:06 UTC, emersonbroga commented on src/sidebarHome.json
> +      "title": "Escotilhas de escape",
Fiquei também confuso nessa parte, vou seguir sua sugestão de "Saídas de emergência", faz muito mais sentido que a tradução literal. Obrigado.

2023-04-26 13:15 UTC, emersonbroga commented on src/sidebarLearn.json
> +          "title": "Escalabilidade vertical com redutor e contexto",
Será que "Escalando com Reducer e Context" seria melhor?

2023-04-26 13:20 UTC, natrodrigo commented on src/sidebarLearn.json
> +          "title": "Atualizando matrizes no estado",
> @natrodrigo mas listas são uma outra estrutura de dados bem definida. Acho que temos que tentar ser fiéis ao texto original nesse ponto

Mas não existe um objeto 'lista' no JS @jotaRenan. Não acho que isso gera um confluto

Então acho que o que mais faz sentido é usar a palavra Array mesmo então, porque na tradução do MDN eles não traduzem esse termo. Vetores e matrizes são mais utilizados em programação dentro da Engenharia em um contexto geralmente matemático.

2023-04-26 13:24 UTC, natrodrigo commented on src/sidebarLearn.json
> +          "title": "Escalabilidade vertical com redutor e contexto",
> Emerson, por que voce preferiu incluir a palavra "vertical" nesse título? Na tradução atual, o termo `reducer` não é traduzido. Acho que faz sentido, e você? Já `Context` é traduzido - o que será que o resto da comunidade pensa sobre isso? Pra mim, é um conceito de react e, por isso, deveria manter o nome próprio sem tradução.

Eu acredito que tanto `Reducer` quanto `Context` são termos específicos do React assim como `Effect` e etc, e devem ser mantidos na forma original.

2023-04-26 13:27 UTC, ErickRock commented on src/sidebarLearn.json
> +      "title": "Descrevendo a IU",
Será que não seria bacana deixar essa parte como "Descrevendo a UI" ao invés de IU?

2023-04-26 13:30 UTC, ErickRock commented on src/sidebarLearn.json
> +          "title": "Ciclo de Vida dos Efeitos Reativos",
Qual padrão seria ideal seguirmos? Alguns termos técnicos me parecem ideal deixar sem a tradução, padronizando.
"Ciclo de Vida dos Reactive Effects" o que vocês acham?

2023-04-26 13:32 UTC, natrodrigo commented on src/sidebarLearn.json
> +      "title": "Descrevendo a IU",
> Será que não seria bacana deixar essa parte como "Descrevendo a UI" ao invés de IU?

@emersonbroga Eu traduzi esse termo como `Construindo a UI` neste PR #660 .

A ideia geral deste tópico é explicar como estruturar a UI usando States e Componentes. A palavra inglesa `Describing` tem esse sentido, mas a palavra brasileira `Descrevendo` não tem. Acredito que faz mais sentido manter `Construindo a UI` ou algum termo semelhante.

2023-04-26 13:32 UTC, ErickRock commented on src/sidebarLearn.json
> +          "title": "Escalabilidade vertical com redutor e contexto",
Concordo com o @natrodrigo, assim mantemos uma padronização mais amigável.

2023-04-26 13:34 UTC, natrodrigo commented on src/sidebarLearn.json
> +          "title": "Ciclo de Vida dos Efeitos Reativos",
> 

Eu sugiro traduzir a palavra `Reactive`, mas não a `Effects`.

2023-04-26 13:47 UTC, natrodrigo requested changes

2023-04-26 13:47 UTC, natrodrigo commented on src/sidebarLearn.json
> +          "title": "Escrevendo marcação com JSX",
Traduzi a palavra `markup` como `tag` neste PR: #660

Sugiro -> "Escrevendo Tags com JSX"

2023-04-26 13:47 UTC, natrodrigo commented on src/sidebarLearn.json
> +          "title": "Passando Props a um Componente",
Sugiro

"Passando Props para um Componente"

2023-04-26 13:47 UTC, natrodrigo commented on src/sidebarLearn.json
> +          "title": "Seu primeiro Componente",
Sugiro

"Seu Primeiro Componente"

Para manter o padrão de caixa alta do original.

2023-04-26 13:53 UTC, natrodrigo commented on src/sidebarLearn.json
> +          "title": "Mantendo seu Componente Puro",
Sugiro manter o plural do original:

"Mantendo seus Componentes Puros"

2023-04-26 14:43 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Escrevendo marcação com JSX",
@natrodrigo, para facilitar a vida do autor da PR ao sugerir alterações simples, vc pode clicar nesse botao para que a UI do github possibilite o merge da sugestao com apenas 1 clique 👍 👍 👍  .  
<img width="82" alt="image" src="https://user-images.githubusercontent.com/14653741/234612142-ed344e89-ae1f-4cb6-a555-5d5fe8225740.png">

2023-04-26 14:45 UTC, jotaRenan commented on src/sidebarLearn.json
> +      "title": "Descrevendo a IU",
Também acho que manter "UI" não traz prejuízo à tradução. Quanto à "Construindo/descrevendo", não tenho opinião.

2023-04-26 14:46 UTC, jotaRenan commented on src/sidebarLearn.json
> +          "title": "Escalabilidade vertical com redutor e contexto",
@emersonbroga "Scale up" é de fato uma [expressão](https://dictionary.cambridge.org/us/dictionary/english/scale-up), portanto faz sentido adaptarmos. Acho que "Escalando" fica adequado :+1:.

2023-04-27 02:10 UTC, jhonmike commented
Pessoal a sugestão é deixar as paginas de UI por ultimo, porque elas ainda podem receber muitas alterações, ta escrito na issue de tradução, assim que possivel vou revisar o PR, mas temos o risco de termos que tratar muitos conflitos até a versão final do site!

2023-04-28 11:40 UTC, jhonmike reviewed
Ficou da hora 👏, apenas 2 sugestões mesmo, vê o que acha!

2023-04-28 11:40 UTC, jhonmike commented on src/sidebarBlog.json
> +      "sectionHeader": "MANTENHA-SE INFORMADO"
Será se não é o caso de traduzir os titulos abaixo?

2023-04-28 11:40 UTC, jhonmike commented on src/sidebarLearn.json
> +      "title": "Descrevendo a IU",
também gosto do UI

2023-05-10 16:28 UTC, merged