Translated 'Rendering Lists' page
reactjs/pt-br.react.dev pull request #670
Opened 2023-04-27 19:37 UTC by TarsiSurdi

Esta PR traduz a página [Rendering Lists](https://react.dev/learn/rendering-lists) para Português do Brasil.

2023-04-27 21:06 UTC, lirbre commented on src/content/learn/rendering-lists.md
> +As únicas diferenças entre os itens da lista são seus conteúdos, seus dados. Você comumente precisará exibir diversas instâncias do mesmo componente usando diferentes dados ao construir interfaces: d
```suggestion
As únicas diferenças entre os itens da lista são seus conteúdos, seus dados. Você comumente precisará exibir diversas instâncias do mesmo componente usando diferentes dados ao construir interfaces: de listas de comentários a galerias de fotos de perfil. Nessas situações, você pode armazenar esses dados em objetos ou arrays JavaScript e usar métodos como [`map()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) e [`filter()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) para renderizar listas de componentes a partir deles.
```

2023-04-27 22:41 UTC, jhonmike commented on src/content/learn/rendering-lists.md
> +As únicas diferenças entre os itens da lista são seus conteúdos, seus dados. Você comumente precisará exibir diversas instâncias do mesmo componente usando diferentes dados ao construir interfaces: d
```suggestion
As únicas diferenças entre os itens da lista são seus conteúdos, seus dados. Você comumente precisará exibir diversas instâncias do mesmo componente usando diferentes dados ao construir interfaces: de listas de comentários a galerias de fotos de perfil. Nessas situações, você pode armazenar esses dados em objetos ou arrays JavaScript e usar métodos como [`map()`](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/map) e [`filter()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) para renderizar listas de componentes a partir deles.
```

2023-04-27 22:41 UTC, jhonmike commented on src/content/learn/rendering-lists.md
>  Warning: Each child in a list should have a unique "key" prop.
Da para traduzir esse trecho

2023-04-27 22:41 UTC, jhonmike commented on src/content/learn/rendering-lists.md
> +Arrow functions contendo `=> {` são ditas como havendo um ["corpo de bloco".](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#function_body) Elas deixam co
```suggestion
Arrow functions contendo `=> {` são ditas como havendo um ["corpo de bloco".](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Functions/Arrow_functions#function_body) Elas deixam com que você escreva mais de uma linha de código, mas você *precisa* escrever uma declaração `return` você mesmo. Caso esquecida, nada é retornado!
```

2023-04-27 22:41 UTC, jhonmike commented on src/content/learn/rendering-lists.md
>  Warning: Each child in a list should have a unique "key" prop.
aqui também

2023-04-27 22:41 UTC, jhonmike commented on src/content/learn/rendering-lists.md
> +* **Dados gerados localmente:** Se seus dados são gerados e persistidos localmente (ex. anotações em um aplicativo de notas), use um contador incremental, [`crypto.randomUUID()`](https://developer.mo
```suggestion
* **Dados gerados localmente:** Se seus dados são gerados e persistidos localmente (ex. anotações em um aplicativo de notas), use um contador incremental, [`crypto.randomUUID()`](https://developer.mozilla.org/pt-BR/docs/Web/API/Crypto/randomUUID) ou um pacote como [`uuid`](https://www.npmjs.com/package/uuid) ao criar itens.
```

2023-04-27 23:13 UTC, glauberbrack commented on src/content/learn/rendering-lists.md
> +Você frequentemente gostará de exibir múltiplos componentes similares a partir de uma coleção de dados. Você pode usar os [métodos de array JavaScript](https://developer.mozilla.org/docs/Web/JavaScri
Tu pode usar as traduções do site do mozilla.
https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/filter
https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/map

2023-04-28 13:41 UTC, alexandredev3 commented
Obrigado pela sua contribuição, @TarsiSurdi! Deixei algumas reviews para sua avaliação.

2023-04-28 14:36 UTC, TarsiSurdi commented
> Obrigado pela sua contribuição, @TarsiSurdi! Deixei algumas reviews para sua avaliação.

Eu quem agradeço, porém você está certo em ter enviado suas reviews? Não as encontro em lugar algum...

2023-04-28 14:47 UTC, TarsiSurdi commented on src/content/learn/rendering-lists.md
> +Você quer apenas os itens onde `profession` seja `'chemist'`. A função "teste" para isso se parece com `(person) => person.profession === 'chemist'`. Aqui está como juntar tudo isso:
Gostei das correções porém o `. Profession` ali está errado 😅

2023-04-28 14:50 UTC, TarsiSurdi commented on src/content/learn/rendering-lists.md
> +1. **Crie** um novo array de apenas pessoas “chemist”, `chemists`, chamando `filter()` em `people` e filtrando por `person.profession === 'chemist'`:
Acho importante manter a relação com a variável `chemists` feita depois da explicação sobre o que ela contém

2023-04-28 21:47 UTC, TarsiSurdi commented on src/content/learn/rendering-lists.md
> +2. Agora **mapeie** sobre `chemists`:
Com base na [definição do método na MDN](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/map) e por se tratar de um termo da área acredito que seja melhor deixar como está.

2023-04-28 21:58 UTC, TarsiSurdi commented on src/content/learn/rendering-lists.md
> +Aviso: Cada filho em uma lista deve haver uma prop "key" única.
Hmmm, não vejo necessidade do warning ser traduzido de uma maneira tão verbosa, no meu ver os termos cada e única já dão a conotação necessária.
Única alteração que fiz foi trocar "haver" para "ter"

2023-04-28 22:03 UTC, TarsiSurdi commented on src/content/learn/rendering-lists.md
> +Você precisa dar a cada item do array uma `key` -- uma string ou um número o qual o identifica unicamente dentre os demais itens naquele array:
Acho que conjugação da sua sugestão está errada, na frase "uma string ou um número o qual o identifica unicamente" nos referimos ao termo "item", no singular. 
Dito isto, o entendimento pode ser melhorado reescrevendo dessa forma: "uma string ou um número que o identifique unicamente"

2023-04-28 22:05 UTC, TarsiSurdi commented on src/content/learn/rendering-lists.md
> +Elementos JSX diretamente dentro de um chamado `map()` sempre precisam de keys!
Que tal "Elementos JSX retornados por um chamado `map()` sempre precisam de keys!"?

2023-04-28 22:12 UTC, TarsiSurdi commented on src/content/learn/rendering-lists.md
> +* **Dados de uma base de dados:** Se seus dados estão vindo de uma base de dados, você pode usar as keys/IDs desta, os quais são únicos por natureza.
Acredito que dessa forma a leitura fique um pouco repetitiva visto que no início da frase o termo "dado" já é bastante citado e apenas "base" soe um pouco estranho

2023-04-28 22:35 UTC, TarsiSurdi commented on src/content/learn/rendering-lists.md
> +#### Listas aninhadas em um componente {/*nested-lists-in-one-component*/}
Encadeado dá o sentido de que uma lista está após a outra, não em seu interior.

2023-04-28 23:22 UTC, alexandredev3 commented on src/content/learn/rendering-lists.md
> +Elementos JSX diretamente dentro de um chamado `map()` sempre precisam de keys!
Que tal substituir a palavra "chamado" por sua forma feminina? Eu percebo que a comunidade tende a utilizar mais a palavra "chamada" no gênero feminino.

2023-04-30 01:08 UTC, alexandredev3 requested changes

2023-04-30 01:08 UTC, alexandredev3 commented on src/content/learn/rendering-lists.md
> +**Note que a `key` é especificada no `<Recipe>` propriamente dito ao invés de na `div` raiz retornada por `Recipe`.** Isso se deve ao fato de que essa `key` é diretamente necessária dentro do context
Eu acho que a palavra "circundante" não fica muito claro, acho melhor substituir por "em que o componente está sendo renderizado"

```suggestion
**Note que a `key` é especificada no `<Recipe>` propriamente dito ao invés de na `div` raiz retornada por `Recipe`.** Isso se deve ao fato de que essa `key` é diretamente necessária dentro do contexto do array em que o componente está sendo renderizado. Anteriormente, você tinha um array de `<div>`s então cada uma delas precisava de uma `key`, mas agora você tem um array de `<Recipe>`s. Em outras palavras, quando você extrai um componente, não se esqueça de deixar a `key` fora da JSX que você copia e cola.
```

2023-04-30 01:08 UTC, alexandredev3 commented on src/content/learn/rendering-lists.md
> +Lembre-se, fragmentos (comumente escritos como `<> </>`) deixam com que você agrupe nós JSX sem adicionar `<div>`s extras!
```suggestion
Lembre-se, fragmentos (são comumente escritos como `<> </>`) deixam com que você agrupe nós JSX sem adicionar `<div>`s extras!
```

2023-04-30 15:10 UTC, TarsiSurdi commented on src/content/learn/rendering-lists.md
> +Lembre-se, fragmentos (comumente escritos como `<> </>`) deixam com que você agrupe nós JSX sem adicionar `<div>`s extras!
Acredito que isso dificulte o entendimento da frase, no entanto o restante das sugestões é bastante válido!

2023-04-30 15:11 UTC, TarsiSurdi reviewed
Aprovadas sugestões de @alexandredev3

2023-05-02 11:31 UTC, jhonmike approved these changes

2023-05-02 11:35 UTC, merged