docs(pt-br): Translate you-might-not-need-an-effect.md
reactjs/pt-br.react.dev pull request #675
Opened 2023-04-29 22:37 UTC by augustodg2

This PR translates the page "You Might Not Need an Effect" to pt-BR

2023-05-02 12:57 UTC, t0in approved these changes

2023-05-05 12:07 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Effects são um escape do paradigma do React. Eles te permitem "dar um passo para fora" do React e sincronizar seus componentes com algum serviço externo, como um widget não React, a rede ou o DOM do
```suggestion
Effects são um escape do paradigma do React. Eles te permitem "dar um passo para fora" do React e sincronizar seus componentes com algum serviço externo, como um widget não React, a rede ou o DOM do navegador. Se não houver nenhum sistema externo envolvido (por exemplo, se você quiser atualizar o estado de um componente quando algumas props ou state mudarem), você não deveria precisar de um Effect. Remover Effects desnecessários tornará seu código mais compreensível, mais rápido de executar e menos propenso a erros.
```

2023-05-05 13:57 UTC, TarsiSurdi requested changes
Fiz diversas melhorias à tradução, dentre elas a maior parte se resume a conformar ao [GLOSSARY](https://github.com/reactjs/pt-br.react.dev/blob/main/GLOSSARY.md) com a tradução de termos comuns como _state_, _prop_ ou _event handler_. No geral a página está ótima e de fácil entendimento em nosso idioma, parabéns!

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +### Ajustando algum estado quando uma prop é alterada {/*adjusting-some-state-when-a-prop-changes*/}
```suggestion
### Ajustando algum state quando uma prop é alterada {/*adjusting-some-state-when-a-prop-changes*/}
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Às vezes, você pode querer redefinir ou ajustar uma parte do estado em uma alteração de prop, mas não todo ele.
```suggestion
Às vezes, você pode querer redefinir ou ajustar uma parte do state em uma alteração de prop, mas não todo ele.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Esse componente `List` recebe uma lista de `items` como uma prop e mantém o item selecionado na variável de estado `selection`. Você deseja redefinir a `selection` para `null` sempre que a prop `item
```suggestion
Este componente `List` recebe uma lista de `items` como uma prop e mantém o item selecionado na variável de estado `selection`. Você deseja redefinir a `selection` para `null` sempre que a prop `items` receber um array diferente:
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Isso também não é ideal. Toda vez que os `items` mudarem, a `List` e seus componentes filhos serão renderizados com um valor `selection` desatualizado no início. Em seguida, o React atualizará o DOM
```suggestion
Isto também não é ideal. Toda vez que os `items` mudarem, a `List` e seus componentes filhos serão renderizados com um valor `selection` desatualizado no início. Em seguida, o React atualizará o DOM e executará os Effects. Por fim, a chamada `setSelection(null)` causará outra re-renderização da `List` e de seus componentes filhos, reiniciando todo o processo novamente.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Comece excluindo o Effect. Em vez disso, ajuste o estado diretamente durante a renderização:
```suggestion
Comece excluindo o Effect. Em vez disso, ajuste o state diretamente durante a renderização:
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +  // Melhor: Ajustar o estado durante a renderização
```suggestion
  // Melhor: Ajustar o state durante a renderização
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +[Armazenar informações de renderizações anteriores](/reference/react/useState#storing-information-from-previous-renders) dessa maneira pode ser difícil de entender, mas é melhor do que atualizar o me
```suggestion
[Armazenar informações de renderizações anteriores](/reference/react/useState#storing-information-from-previous-renders) dessa maneira pode ser difícil de entender, mas é melhor do que atualizar o mesmo state em um Effect. No exemplo acima, `setSelection` é chamado diretamente durante uma renderização. O React irá re-renderizar a `List` *imediatamente* após sair com uma instrução `return`. O React ainda não renderizou os filhos da `List` ou atualizou o DOM, então isso permite que os filhos da `List` pulem a renderização do valor obsoleto da `selection`.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Quando você atualiza um componente durante a renderização, o React joga fora o JSX retornado e imediatamente reinicia a renderização. Para evitar repetições em cascata muito lentas, o React só permit
```suggestion
Quando você atualiza um componente durante a renderização, o React descarta o JSX retornado e imediatamente reinicia a renderização. Para evitar repetições em cascata muito lentas, o React só permite que você atualize o state do *mesmo* componente durante uma renderização. Se você atualizar o state de outro componente durante uma renderização, verá um erro. Uma condição como `items !== prevItems` é necessária para evitar loops. Você pode ajustar o state dessa forma, mas quaisquer outros efeitos colaterais (como alterar o DOM ou definir timeouts) devem ficar em manipuladores de evento ou Effects para [manter os componentes puros](/learn/keeping-components-pure).
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +**Embora esse padrão seja mais eficiente do que um Effect, a maioria dos componentes também não deve precisar dele.** Não importa como você o faça, o ajuste do estado com base em props ou outro estad
```suggestion
**Embora esse padrão seja mais eficiente do que um Effect, a maioria dos componentes também não deve precisar dele.** Não importa como você o faça, o ajuste do state com base em props ou outro state torna o fluxo de dados mais difícil de entender e depurar. Sempre verifique se, em vez disso, você pode [redefinir todo o estado com uma chave](#resetting-all-state-when-a-prop-changes) ou [calcular tudo durante a renderização](#updating-state-based-on-props-or-state). Por exemplo, em vez de armazenar (e redefinir) o *item* selecionado, você pode armazenar o *ID do item selecionado:*
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Agora não há necessidade de "ajustar" o estado. Se o item com o ID selecionado estiver na lista, ele permanecerá selecionado. Se não estiver, a `selection` calculada durante a renderização será `null
```suggestion
Agora não há necessidade de "ajustar" o state. Se o item com o ID selecionado estiver na lista, ele permanecerá selecionado. Se não estiver, a `selection` calculada durante a renderização será `null` porque nenhum item correspondente foi encontrado. Esse comportamento é diferente, mas indiscutivelmente melhor porque a maioria das alterações nos `items` preserva a seleção.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +### Compartilhamento de lógica entre event handlers {/*sharing-logic-between-event-handlers*/}
```suggestion
### Compartilhamento de lógica entre manipuladores de evento {/*sharing-logic-between-event-handlers*/}
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Digamos que você tenha uma página de produto com dois botões (Buy e Checkout) que permitem que você compre o produto. Você deseja exibir uma notificação sempre que o usuário colocar o produto no carr
```suggestion
Digamos que você tenha uma página de produto com dois botões (Buy e Checkout) que permitem que você compre o produto. Você deseja exibir uma notificação sempre que o usuário colocar o produto no carrinho. Chamar `showNotification()` nos manipuladores de cliques dos dois botões parece repetitivo, portanto, você pode se sentir tentado a colocar essa lógica em um Effect:
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +**Quando não tiver certeza se algum código deve estar em um Effect ou em um manipulador de eventos, pergunte a si mesmo *por que* esse código precisa ser executado. Use Effects somente para códigos q
```suggestion
**Quando não tiver certeza se algum código deve estar em um Effect ou em um manipulador de eventos, pergunte a si mesmo *por que* esse código precisa ser executado. Use Effects somente para códigos que devem ser executados *porque* o componente foi exibido ao usuário.** Neste exemplo, a notificação deve aparecer porque o usuário *pressionou o botão*, não porque a página foi exibida! Exclua o Effect e coloque a lógica compartilhada em uma função chamada de ambos os manipuladores de evento:
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +  // ✅ Bom: A lógica específica do evento é chamada pelos event handlers
```suggestion
  // ✅ Bom: A lógica específica do evento é chamada pelos manipuladores
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Esse componente `Form` envia dois tipos de solicitações POST. Ele envia um evento de analytics quando é montado. Quando você preencher o formulário e clicar no botão Submit, ele enviará uma solicitaç
```suggestion
Este componente `Form` envia dois tipos de solicitações POST. Ele envia um evento de analytics quando é montado. Quando você preencher o formulário e clicar no botão Submit, ele enviará uma solicitação POST ao endpoint `/api/register`:
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +No entanto, a solicitação POST `/api/register` não é causada pelo formulário que está sendo _exibido_. Você só deseja enviar a solicitação em um momento específico: quando o usuário pressiona o botão
```suggestion
No entanto, a solicitação POST `/api/register` não é causada pelo formulário que está sendo _exibido_. Você só deseja enviar a solicitação em um momento específico: quando o usuário pressiona o botão. Isso só deve acontecer _naquela interação específica_. Exclua o segundo Effect e mova essa solicitação POST para o manipulador de evento:
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +    // ✅ Bom: A lógica específica do evento está no event handler.
```suggestion
    // ✅ Bom: A lógica específica do evento está no manipulador.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Ao decidir se deve colocar alguma lógica em um event handler ou em um Effect, a principal pergunta que precisa ser respondida é _que tipo de lógica_ ela é da perspectiva do usuário. Se essa lógica fo
```suggestion
Ao decidir se deve colocar alguma lógica em um manipulador de evento ou em um Effect, a principal pergunta que precisa ser respondida é _que tipo de lógica_ ela é da perspectiva do usuário. Se essa lógica for causada por uma interação específica, mantenha-a no manipulador de evento. Se for causada pelo fato de o usuário _ver_ o componente na tela, mantenha-a no Effect.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Às vezes, você pode se sentir tentado a encadear Effects que ajustam uma parte do estado com base em outro estado:
```suggestion
Às vezes, você pode se sentir tentado a encadear Effects que ajustam uma parte do state com base em outro state:
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +  // 🔴 Evitar: Cadeias de Effects que ajustam o estado apenas para acionar uns aos outros
```suggestion
  // 🔴 Evitar: Cadeias de Effects que ajustam o state apenas para acionar uns aos outros
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Mesmo que isso não fosse lento, à medida que seu código evolui, você se depara com casos em que a "cadeia" que você escreveu não atende aos novos requisitos. Imagine que você esteja adicionando uma m
```suggestion
Mesmo que isso não fosse lento, à medida que seu código evolui, você se depara com casos em que a "cadeia" que você escreveu não atende aos novos requisitos. Imagine que você esteja adicionando uma maneira de percorrer o histórico dos movimentos do jogo. Você faria isso atualizando cada variável de state para um valor do passado. Entretanto, definir o state `card` como um valor do passado acionaria a cadeia de Effects novamente e alteraria os dados que você está mostrando. Esse tipo de código costuma ser rígido e frágil.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Nesse caso, é melhor calcular o que for possível durante a renderização e ajustar o estado no event handler:
```suggestion
Neste caso, é melhor calcular o que for possível durante a renderização e ajustar o state no manipulador de evento:
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +    // ✅ Calcular todo o próximo estado no event handler
```suggestion
    // ✅ Calcular todo o próximo state no manipulador de evento
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Isso é muito mais eficiente. Além disso, se você implementar uma maneira de visualizar o histórico do jogo, agora poderá definir cada variável de estado para um movimento do passado sem acionar a cad
```suggestion
Isso é muito mais eficiente. Além disso, se você implementar uma maneira de visualizar o histórico do jogo, agora poderá definir cada variável de state para um movimento do passado sem acionar a cadeia de Effects que ajusta todos os outros valores. Se precisar reutilizar a lógica entre vários manipuladores de evento, você poderá [extrair uma função](#sharing-logic-between-event-handlers) e chamá-la a partir desses manipuladores.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Lembre-se de que, dentro dos event handlers, [o estado se comporta como uma snapshot](/learn/state-as-a-snapshot). Por exemplo, mesmo depois de chamar `setRound(round + 1)`, a variável `round` reflet
```suggestion
Lembre-se de que, dentro dos manipuladores de evento, [o estado se comporta como uma snapshot](/learn/state-as-a-snapshot). Por exemplo, mesmo depois de chamar `setRound(round + 1)`, a variável `round` refletirá o valor no momento em que o usuário clicou no botão. Se você precisar usar o próximo valor para cálculos, defina-o manualmente como `const nextRound = round + 1`.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Em alguns casos, você *não pode* calcular o próximo estado diretamente no event handler. Por exemplo, imagine um formulário com vários dropdowns em que as opções do próximo dropdown dependem do valor
```suggestion
Em alguns casos, você *não pode* calcular o próximo state diretamente no manipulador de evento. Por exemplo, imagine um formulário com vários menus suspensos em que as opções do próximo menu dependem do valor selecionado do menu anterior. Nesse caso, uma cadeia de Effects é apropriada porque você está sincronizando com a rede.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Digamos que você esteja escrevendo um componente `Toggle` com um estado interno `isOn` que pode ser `true` ou `false`. Há algumas maneiras diferentes de alterná-lo (clicando ou arrastando). Você dese
```suggestion
Digamos que você esteja escrevendo um componente `Toggle` com um state interno `isOn` que pode ser `true` ou `false`. Há algumas maneiras diferentes de alterná-lo (clicando ou arrastando). Você deseja notificar o componente pai sempre que o estado interno do `Toggle` for alterado, portanto, você expõe um evento `onChange` e o chama a partir de um Effect:
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +  // 🔴 Evitar: O handler onChange é executado tarde demais
```suggestion
  // 🔴 Evitar: O manipulador onChange é executado tarde demais
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Como anteriormente, isso não é ideal. O `Toggle` atualiza seu estado primeiro, e o React atualiza a tela. Em seguida, o React executa o Effect, que chama a função `onChange` passada de um componente
```suggestion
Como anteriormente, isso não é ideal. O `Toggle` atualiza seu state primeiro, e o React atualiza a tela. Em seguida, o React executa o Effect, que chama a função `onChange` passada de um componente pai. Agora o componente pai atualizará seu próprio state, iniciando outra passagem de renderização. Seria melhor fazer tudo em uma única passagem.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Exclua o Effect e, em vez disso, atualize o estado de *ambos* os componentes no mesmo event handler:
```suggestion
Exclua o Effect e, em vez disso, atualize o state de *ambos* os componentes no mesmo manipulador de evento:
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Com essa abordagem, tanto o componente `Toggle` quanto seu componente pai atualizam seu estado durante o evento. O React [processa em lote atualizações](/learn/queueing-a-series-of-state-updates) de
```suggestion
Com essa abordagem, tanto o componente `Toggle` quanto seu componente pai atualizam seu state durante o evento. O React [processa em lote atualizações](/learn/queueing-a-series-of-state-updates) de diferentes componentes juntos, de modo que haverá apenas uma passagem de renderização.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Você também pode remover completamente o estado e, em vez disso, receber `isOn` do componente pai:
```suggestion
Você também pode remover completamente o state e, em vez disso, receber `isOn` do componente pai:
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +["Elevar o estado"](/learn/sharing-state-between-components) permite que o componente pai controle totalmente o `Toggle` alternando o estado do próprio componente pai. Isso significa que o componente
```suggestion
["Elevar o state"](/learn/sharing-state-between-components) permite que o componente pai controle totalmente o `Toggle` alternando o state do próprio componente pai. Isso significa que o componente pai terá que conter mais lógica, mas haverá menos state geral com o qual se preocupar. Sempre que você tentar manter duas variáveis de state diferentes sincronizadas, tente elevar o state em vez disso!
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +No React, os dados fluem dos componentes pai para seus filhos. Quando você vê algo errado na tela, pode rastrear a origem da informação subindo a cadeia de componentes até encontrar o componente que
```suggestion
No React, os dados fluem dos componentes pai para seus filhos. Quando você vê algo errado na tela, pode rastrear a origem da informação subindo a cadeia de componentes até encontrar o componente que passa a prop errada ou tem o state errado. Quando os componentes filhos atualizam o state de seus componentes pais em Effects, o fluxo de dados se torna muito difícil de rastrear. Como tanto o componente filho quanto o pai precisam dos mesmos dados, deixe o componente pai buscar esses dados e, em vez disso, *passá-los* para o filho:
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Às vezes, seus componentes podem precisar escutar alguns dados fora do estado do React. Esses dados podem ser de uma biblioteca de terceiros ou de uma API integrada do navegador. Como esses dados pod
```suggestion
Às vezes, seus componentes podem precisar escutar alguns dados fora do state do React. Esses dados podem ser de uma biblioteca de terceiros ou de uma API integrada do navegador. Como esses dados podem ser alterados sem o conhecimento do React, você precisa se inscrever manualmente em seus componentes. Isso geralmente é feito com um Effect, por exemplo:
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Aqui, o componente se inscreve em um armazenamento de dados externo (nesse caso, a API `navigator.onLine` do navegador). Como essa API não existe no servidor (portanto, não pode ser usada para o HTML
```suggestion
Aqui, o componente se inscreve em um armazenamento de dados externo (nesse caso, a API `navigator.onLine` do navegador). Como essa API não existe no servidor (portanto, não pode ser usada para o HTML inicial), inicialmente o state é definido como `true`. Sempre que o valor desse armazenamento de dados for alterado no navegador, o componente atualizará seu estado.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Essa abordagem é menos propensa a erros do que a sincronização manual de dados mutáveis para o estado do React com um Effect. Normalmente, você escreverá um Hook personalizado como o `useOnlineStatus
```suggestion
Essa abordagem é menos propensa a erros do que a sincronização manual de dados mutáveis para o state do React com um Effect. Normalmente, você escreverá um Hook personalizado como o `useOnlineStatus()` acima para não precisar repetir esse código nos componentes individuais. [Leia mais sobre como assinar armazenamentos externos a partir de componentes React](/reference/react/useSyncExternalStore)
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Você *não* precisa mover essa busca para um event handler.
```suggestion
Você *não* precisa mover essa busca para um manipulador de evento.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +**Esses problemas se aplicam a qualquer biblioteca de interface do usuário, não apenas ao React. Resolvê-los não é trivial, e é por isso que os [frameworks modernos](/learn/start-a-new-react-project#
```suggestion
**Esses problemas se aplicam a qualquer biblioteca de interface do usuário, não apenas ao React. Resolvê-los não é trivial, e é por isso que os [frameworks modernos](/learn/start-a-new-react-project#production-grade-react-frameworks) fornecem mecanismos internos de busca de dados mais eficientes do que a busca de dados nos Effects.**
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Se você não usa um framework (e não quer criar o sua próprio), mas gostaria de tornar a busca de dados do Effects mais ergonômica, considere extrair sua lógica de busca em um Hook personalizado, como
```suggestion
Se você não usa um framework (e não quer criar o seu próprio), mas gostaria de tornar a busca de dados dos Effects mais ergonômica, considere extrair sua lógica de busca em um Hook personalizado, como neste exemplo:
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +- Para redefinir o estado de uma árvore de componentes inteira, passe uma `key` diferente para ela.
```suggestion
- Para redefinir o state de uma árvore de componentes inteira, passe uma `key` diferente para ela.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +- Para redefinir um determinado estado em resposta a uma alteração de prop, ajuste-o durante a renderização.
```suggestion
- Para redefinir um determinado state em resposta a uma alteração de prop, ajuste-o durante a renderização.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +- Se você precisar atualizar o estado de vários componentes, é melhor fazê-lo durante um único evento.
```suggestion
- Se você precisar atualizar o state de vários componentes, é melhor fazê-lo durante um único evento.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +- Sempre que você tentar sincronizar variáveis de estado em diferentes componentes, considere elevar o estado.
```suggestion
- Sempre que você tentar sincronizar variáveis de state em diferentes componentes, considere elevar o state.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Simplifique esse componente removendo todo o estado e os Effects desnecessários.
```suggestion
Simplifique esse componente removendo todo o state e os Effects desnecessários.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Se você puder calcular algo durante a renderização, não precisará de estado ou de um Effect que o atualize.
```suggestion
Se você puder calcular algo durante a renderização, não precisará de state ou de um Effect que o atualize.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Há apenas duas partes essenciais de estado neste exemplo: a lista de `todos` e a variável de estado `showActive` que representa se a caixa de seleção está marcada. Todas as outras variáveis de estado
```suggestion
Há apenas duas partes essenciais de estado neste exemplo: a lista de `todos` e a variável de state `showActive` que representa se a caixa de seleção está marcada. Todas as outras variáveis de state são [redundantes](/learn/choosing-the-state-structure#avoid-redundant-state) e podem ser calculadas durante a renderização. Isso inclui o `footer`, que você pode mover diretamente para a JSX circundante.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Neste exemplo, a filtragem dos *todos* foi extraída em uma função separada chamada `getVisibleTodos()`. Essa função contém uma chamada `console.log()` dentro dela, o que o ajuda a perceber quando est
```suggestion
Neste exemplo, a filtragem dos *todos* foi extraída em uma função separada chamada `getVisibleTodos()`. Essa função contém uma chamada `console.log()` dentro dela, o que o ajuda a perceber quando está sendo chamada. Alterne a opção "Show only active todos" e perceba que isso faz com que a função `getVisibleTodos()` seja executada novamente. Isso é esperado porque os *todos* visíveis mudam quando você alterna quais devem ser exibidos.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Remova a variável de estado e o Effect e, em vez disso, adicione uma chamada `useMemo` para armazenar em cache o resultado da chamada `getVisibleTodos()`:
```suggestion
Remova a variável de state e o Effect e, em vez disso, adicione uma chamada `useMemo` para armazenar em cache o resultado da chamada `getVisibleTodos()`:
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Com essa alteração, a função `getVisibleTodos()` será chamada somente se `todos` ou `showActive` forem alterados. A digitação na entrada altera apenas a variável de estado `text`, portanto, não acion
```suggestion
Com essa alteração, a função `getVisibleTodos()` será chamada somente se `todos` ou `showActive` forem alterados. A digitação na entrada altera apenas a variável de state `text`, portanto, não aciona uma chamada para `getVisibleTodos()`.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Há também outra solução que não precisa do `useMemo`. Como a variável de estado `text` não pode afetar a lista de todos, você pode extrair o formulário `NewTodo` em um componente separado e mover a v
```suggestion
Há também outra solução que não precisa do `useMemo`. Como a variável de state `text` não pode afetar a lista de todos, você pode extrair o formulário `NewTodo` em um componente separado e mover a variável de estado `text` para dentro dele:
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Essa abordagem também satisfaz os requisitos. Quando você digita na entrada, apenas a variável de estado `text` é atualizada. Como a variável de estado `text` está no componente filho `NewTodo`, o co
```suggestion
Essa abordagem também satisfaz os requisitos. Quando você digita na entrada, apenas a variável de estado `text` é atualizada. Como a variável de state `text` está no componente filho `NewTodo`, o componente pai `TodoList` não será renderizado novamente. É por isso que a função `getVisibleTodos()` não é chamada quando você digita. (Ele ainda seria chamado se o `TodoList` fosse renderizado novamente por outro motivo).
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +#### Redefinir estado sem Effects {/*reset-state-without-effects*/}
```suggestion
#### Redefinir state sem Effects {/*reset-state-without-effects*/}
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Seria bom se houvesse uma maneira de dizer ao React que quando `savedContact.id` é diferente, o formulário `EditContact` é conceitualmente um _formulário de contato diferente_ e não deve preservar o
```suggestion
Seria bom se houvesse uma maneira de dizer ao React que quando `savedContact.id` é diferente, o formulário `EditContact` é conceitualmente um _formulário de contato diferente_ e não deve preservar o state. Você se lembra de alguma maneira?
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Divida o componente `EditContact` em dois. Mova todo o estado do formulário para o componente `EditForm` interno. Exporte o componente externo `EditContact` e faça com que ele passe `savedContact.id`
```suggestion
Divida o componente `EditContact` em dois. Mova todo o state do formulário para o componente `EditForm` interno. Exporte o componente externo `EditContact` e faça com que ele passe `savedContact.id` como a `chave` para o componente interno `EditContact`. Como resultado, o componente interno `EditForm` redefine todo o state do formulário e recria o DOM sempre que você seleciona um contato diferente.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Esse componente `Form` permite que você envie uma mensagem a um amigo. Quando você envia o formulário, a variável de estado `showForm` é definida como `false`. Isso aciona um Effect chamando `sendMes
```suggestion
Esse componente `Form` permite que você envie uma mensagem a um amigo. Quando você envia o formulário, a state de estado `showForm` é definida como `false`. Isso aciona um Effect chamando `sendMessage(message)`, que envia a mensagem (você pode vê-la no console). Depois que a mensagem é enviada, você vê uma caixa de diálogo "Thank you" (Obrigado) com um botão "Open chat" (Abrir bate-papo) que permite que você volte ao formulário.
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Os usuários do seu aplicativo estão enviando muitas mensagens. Para tornar o bate-papo um pouco mais difícil, você decidiu mostrar a caixa de diálogo "Thank you" *primeiro* em vez do formulário. Alte
```suggestion
Os usuários do seu aplicativo estão enviando muitas mensagens. Para tornar o bate-papo um pouco mais difícil, você decidiu mostrar a caixa de diálogo "Thank you" *primeiro* em vez do formulário. Altere a variável de state `showForm` para inicializar com `false` em vez de `true`. Assim que fizer essa alteração, o console mostrará que uma mensagem vazia foi enviada. Alguma coisa nessa lógica está errada!
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +A variável de estado `showForm` determina se deve ser exibido o formulário ou a caixa de diálogo "Thank you". No entanto, você não está enviando a mensagem porque a caixa de diálogo "Thank you" foi _
```suggestion
A variável de state `showForm` determina se deve ser exibido o formulário ou a caixa de diálogo "Thank you". No entanto, você não está enviando a mensagem porque a caixa de diálogo "Thank you" foi _exibida_. Você deseja enviar a mensagem porque o usuário enviou o formulário. Exclua o Effect enganoso e mova a chamada `sendMessage` para dentro do manipulador de evento `handleSubmit`:
```

2023-05-05 13:57 UTC, TarsiSurdi commented on src/content/learn/you-might-not-need-an-effect.md
> +Observe como, nessa versão, apenas _submeter o formulário_ (que é um evento) faz com que a mensagem seja enviada. Isso funciona igualmente bem, independentemente de `showForm` ser inicialmente defini
```suggestion
Perceba como, nessa versão, apenas _submeter o formulário_ (que é um evento) faz com que a mensagem seja enviada. Isso funciona igualmente bem, independentemente de `showForm` ser inicialmente definido como `true` ou `false`. (Defina-o como `false` e não observe nenhuma mensagem extra no console).
```

2023-05-05 13:57 UTC, TarsiSurdi requested changes
Fiz diversas melhorias à tradução, dentre elas a maior parte se resume a conformar ao [GLOSSARY](https://github.com/reactjs/pt-br.react.dev/blob/main/GLOSSARY.md) com a tradução de termos comuns como _state_, _prop_ ou _event handler_. No geral a página está ótima e de fácil entendimento em nosso idioma, parabéns!

2023-05-05 14:14 UTC, augustodg2 commented on src/content/learn/you-might-not-need-an-effect.md
> +Isso é mais complicado que o necessário. É ineficente também: isso faz uma renderização inteira com um valor desatualizado de `fullName`, e depois imediatamente re-renderiza com o valor atualizado. R
"state variable" traduziria para "variável de state", "variável state" ou só "state"?

2023-05-05 14:19 UTC, augustodg2 commented on src/content/learn/you-might-not-need-an-effect.md
> +Esse componente `ProfilePage` recebe uma propriedade `userId`. A página contém um input de comentário e você usa uma variável de estado `comment` para manter seu valor. Um dia, você percebeu um probl
Aqui pode ser um campo? É input no sentido de caixa de texto mesmo

2023-05-05 14:56 UTC, augustodg2 commented on src/content/learn/you-might-not-need-an-effect.md
> +Às vezes, você pode querer redefinir ou ajustar uma parte do estado em uma alteração de prop, mas não todo ele.
```suggestion
Às vezes, você pode querer redefinir ou ajustar algum state específico, sem afetar outros, quando uma prop for alterada.
```

2023-05-05 14:56 UTC, augustodg2 commented on src/content/learn/you-might-not-need-an-effect.md
> +Às vezes, você pode se sentir tentado a encadear Effects que ajustam uma parte do estado com base em outro estado:
```suggestion
Às vezes, você pode se sentir tentado a encadear Effects que ajustam um state com base em outro state:
```

2023-05-05 14:56 UTC, augustodg2 commented on src/content/learn/you-might-not-need-an-effect.md
> +### Inicialização do aplicativo {/*initializing-the-application*/}
```suggestion
### Inicialização da aplicação {/*initializing-the-application*/}
```

2023-05-05 14:56 UTC, augustodg2 commented on src/content/learn/you-might-not-need-an-effect.md
> +Embora talvez ele nunca seja remontado na prática em produção, seguir as mesmas restrições em todos os componentes facilita a movimentação e a reutilização do código. Se alguma lógica precisar ser ex
```suggestion
Embora talvez ele nunca seja remontado na prática em produção, seguir as mesmas restrições em todos os componentes facilita a movimentação e a reutilização do código. Se alguma lógica precisar ser executada *uma vez por carregamento da aplicação* em vez de *uma vez por montagem de componente*, adicione uma variável no nível mais alto para registrar se ela já foi executada:
```

2023-05-05 14:56 UTC, augustodg2 commented on src/content/learn/you-might-not-need-an-effect.md
> +      // ✅ Só é executado uma vez por execução do aplicativo
```suggestion
      // ✅ Só é executado uma vez por execução do aplicativo
```
```suggestion
      // ✅ Só é executado uma vez por execução da aplicação
```

2023-05-05 14:56 UTC, augustodg2 commented on src/content/learn/you-might-not-need-an-effect.md
> +Você também pode executá-lo durante a inicialização do módulo e antes de o aplicativo ser renderizado:
```suggestion
Você também pode executá-lo durante a inicialização do módulo e antes de a aplicação ser renderizada:
```

2023-05-05 14:56 UTC, augustodg2 commented on src/content/learn/you-might-not-need-an-effect.md
> +   // ✅ Só é executado uma vez por execução do aplicativo
```suggestion
   // ✅ Só é executado uma vez por execução da aplicação
```

2023-05-05 14:56 UTC, augustodg2 commented on src/content/learn/you-might-not-need-an-effect.md
> +O código no nível mais alto é executado uma vez quando o componente é importado, mesmo que ele não seja renderizado. Para evitar lentidão ou comportamento inesperado ao importar componentes arbitrári
```suggestion
O código no nível mais alto é executado uma vez quando o componente é importado, mesmo que ele não seja renderizado. Para evitar lentidão ou comportamento inesperado ao importar componentes arbitrários, não use esse padrão em excesso. Mantenha a lógica de inicialização de toda a aplicação em módulos de componentes raiz como `App.js` ou no ponto de entrada da aplicação.
```

2023-05-05 14:56 UTC, augustodg2 commented on src/content/learn/you-might-not-need-an-effect.md
> +Esse Effect é desnecessário. Ele também provavelmente causará bugs. Por exemplo, digamos que seu aplicativo "lembre" o carrinho de compras entre os recarregamentos da página. Se você adicionar um pro
```suggestion
Esse Effect é desnecessário. Ele também provavelmente causará bugs. Por exemplo, digamos que sua aplicação "lembre" o carrinho de compras entre os recarregamentos da página. Se você adicionar um produto ao carrinho uma vez e atualizar a página, a notificação aparecerá novamente. Ela continuará aparecendo toda vez que você atualizar a página desse produto. Isso ocorre porque `product.isInCart` já será `true` no carregamento da página, de modo que o Effect acima chamará `showNotification()`.
```

2023-05-05 14:56 UTC, augustodg2 commented on src/content/learn/you-might-not-need-an-effect.md
> +Muitos aplicativos usam o Effects para iniciar a busca de dados. É bastante comum escrever um Effect de busca de dados como este:
```suggestion
Muitas aplicações usam o Effects para iniciar a busca de dados. É bastante comum escrever um Effect de busca de dados como este:
```

2023-05-05 14:56 UTC, augustodg2 commented on src/content/learn/you-might-not-need-an-effect.md
> +Em geral, sempre que tiver que recorrer à criação de Effects, fique atento para quando puder extrair uma parte da funcionalidade em um Hook personalizado com uma API mais declarativa e específica, co
```suggestion
Em geral, sempre que tiver que recorrer à criação de Effects, fique atento para quando puder extrair uma parte da funcionalidade em um Hook personalizado com uma API mais declarativa e específica, como o `useData` acima. Quanto menos chamadas `useEffect` brutas você tiver em seus componentes, mais fácil será manter sua aplicação.
```

2023-05-05 14:56 UTC, augustodg2 commented on src/content/learn/you-might-not-need-an-effect.md
> +Os usuários do seu aplicativo estão enviando muitas mensagens. Para tornar o bate-papo um pouco mais difícil, você decidiu mostrar a caixa de diálogo "Thank you" *primeiro* em vez do formulário. Alte
```suggestion
Os usuários da sua aplicação estão enviando muitas mensagens. Para tornar o bate-papo um pouco mais difícil, você decidiu mostrar a caixa de diálogo "Thank you" *primeiro* em vez do formulário. Altere a variável de state `showForm` para inicializar com `false` em vez de `true`. Assim que fizer essa alteração, o console mostrará que uma mensagem vazia foi enviada. Alguma coisa nessa lógica está errada!
```

2023-05-05 14:56 UTC, augustodg2 commented on src/content/learn/you-might-not-need-an-effect.md
> +Esse componente `Form` permite que você envie uma mensagem a um amigo. Quando você envia o formulário, a variável de estado `showForm` é definida como `false`. Isso aciona um Effect chamando `sendMes
```suggestion
Esse componente `Form` permite que você envie uma mensagem a um amigo. Quando você envia o formulário, a variável de state `showForm` é definida como `false`. Isso aciona um Effect chamando `sendMessage(message)`, que envia a mensagem (você pode vê-la no console). Depois que a mensagem é enviada, você vê uma caixa de diálogo "Thank you" (Obrigado) com um botão "Open chat" (Abrir bate-papo) que permite que você volte ao formulário.
```

2023-05-07 03:20 UTC, TarsiSurdi approved these changes

2023-05-07 12:59 UTC, augustodg2 commented on src/content/learn/you-might-not-need-an-effect.md
> +Isso é mais complicado que o necessário. É ineficente também: isso faz uma renderização inteira com um valor desatualizado de `fullName`, e depois imediatamente re-renderiza com o valor atualizado. R
```suggestion
Isso é mais complicado que o necessário. É ineficente também: isso faz uma renderização inteira com um valor desatualizado de `fullName`, e depois imediatamente re-renderiza com o valor atualizado. Remova o state e o Effect:
```

2023-05-07 16:59 UTC, augustodg2 commented
Obrigado pela review @TarsiSurdi, acredito que resolvi todas as questões levantadas.

2023-05-08 12:28 UTC, TarsiSurdi approved these changes

2023-05-10 16:37 UTC, merged