docs(pt-br): translated progress.md
reactjs/pt-br.react.dev pull request #678
Opened 2023-05-02 12:17 UTC by felipefreitag

Traduz [progress](https://react.dev/reference/react-dom/components/progress) para pt-BR

2023-05-02 19:46 UTC, TarsiSurdi requested changes
Ótima tradução!
Algumas sugestões de mudanças :)

2023-05-02 19:46 UTC, TarsiSurdi commented on src/content/reference/react-dom/components/progress.md
> +O [componente `<progress>` nativo do browser](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress) permite que você renderize um indicador de progresso.
Será que não seria interessante traduzir _browser_  como navegador mesmo? Foi o que fiz em outras páginas que traduzi.
```suggestion
O [componente `<progress>` nativo do navegador](https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/progress) permite que você renderize um indicador de progresso.
```

2023-05-02 19:46 UTC, TarsiSurdi commented on src/content/reference/react-dom/components/progress.md
> +Para mostrar um indicador de progresso, renderize o componente [`<progress>` nativo do browser](https://developer.mozilla.org/pt-br/docs/Web/HTML/Element/progress).
```suggestion
Para exibir um indicador de progresso, renderize o componente [`<progress>` nativo do browser](https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/progress).
```

2023-05-02 19:46 UTC, TarsiSurdi commented on src/content/reference/react-dom/components/progress.md
> +`<progress>` suporta todas [props comuns de elementos.](/reference/react-dom/components/common#props)
```suggestion
`<progress>` suporta todas as [props comuns dos elementos.](/reference/react-dom/components/common#props)
```

2023-05-02 19:46 UTC, TarsiSurdi commented on src/content/reference/react-dom/components/progress.md
> +* [`max`](https://developer.mozilla.org/pt-br/docs/Web/HTML/Element/progress#attr-max): Um número. Especifica o `value` máximo. O padrão é `1`.
```suggestion
* [`max`](https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/progress#attr-max): Um número. Especifica o `value` máximo. Seu valor padrão é `1`.
```

2023-05-02 19:46 UTC, TarsiSurdi commented on src/content/reference/react-dom/components/progress.md
> +Para mostrar um indicador de progresso, renderize um componente `<progress>`. Você pode passar um número `value` entre `0` e o valor `max` que você especificar. Se você não passar um valor `max`, o p
```suggestion
Para exibir um indicador de progresso, renderize um componente `<progress>`. Você pode passar `value`, um número entre `0` e o valor `max` por você especificado. Se você não passar um valor `max`, o padrão usado será `1`.
```

2023-05-03 19:08 UTC, felipefreitag commented
Sugestões adicionadas!

2023-05-03 20:36 UTC, TarsiSurdi submitted a review, later dismissed

2023-05-03 20:36 UTC, TarsiSurdi commented on src/content/reference/react-dom/components/progress.md
> +Para exibir um indicador de progresso, renderize o componente [`<progress>` nativo do browser](https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/progress).
```suggestion
Para exibir um indicador de progresso, renderize o componente [`<progress>` nativo do navegador](https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/progress).
```
Para ficar igual à tradução do parágrafo de cima

2023-05-03 23:45 UTC, TarsiSurdi approved these changes

2023-05-04 13:21 UTC, buirkan approved these changes

2023-05-04 13:21 UTC, buirkan commented on src/content/reference/react-dom/components/progress.md
> +* [`value`](https://developer.mozilla.org/pt-br/docs/Web/HTML/Element/progress#attr-value): Um número entre `0` e `max`, ou `null` para progresso indeterminado. Especifica o quanto foi feito.
Só um detalhe, na url está pt-br em minúsculo, mas no fim resolve para `pt-BR` sem problemas, se achar necessário da pra colocar `pt-BR` como nas outras urls.
```suggestion
* [`value`](https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/progress#attr-value): Um número entre `0` e `max`, ou `null` para progresso indeterminado. Especifica o quanto foi feito.
```

2023-05-04 14:41 UTC, buirkan approved these changes

2023-05-04 14:47 UTC, TarsiSurdi approved these changes

2023-05-10 13:21 UTC, jhonmike approved these changes

2023-05-10 13:21 UTC, merged