Translate updating-objects-in-state.md
reactjs/pt-br.react.dev pull request #679
Opened 2023-05-02 19:15 UTC by Egpereira

# Tradução do arquivo `updating-objects-in-state.md`

## Dúvidas de tradução
Algumas dúvidas durante a tradução sobre alguns termos que gostaria de segundas opiniões, se possível:
- spread syntax -> sintaxe de espalhamento ([seguindo o termo utilizado pela mdn web docs](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Operators/Spread_syntax))
- snapshot -> mantido como snapshots
- read-only -> somente leitura
- without additional performance or correctness pitfalls. -> sem armadilhas adicionais de desempenho ou corretude

## Links adicionais
- [Página original](https://react.dev/learn/updating-objects-in-state)

2023-05-02 19:59 UTC, TarsiSurdi commented
Concordo com a tradução de _spread syntax_ como sintaxe de espalhamento, assim como feito na #676.
Quanto ao _snapshot_ fiquei bastante em dúvida nas traduções que fiz pois sempre interpretei como "um momento isolado no tempo". Talvez seja um estrangeirismo o qual teremos que incorporar na documentação ou deve-se estabelecer alguma guideline sobre como o traduzir no [GLOSSARY](https://github.com/reactjs/pt-br.react.dev/blob/main/GLOSSARY.md).

2023-05-29 16:35 UTC, dieguesmosken requested changes
sugiro pequenas mudanças na tradução onde comentei anteriormente

2023-05-29 16:35 UTC, dieguesmosken commented on src/content/learn/updating-objects-in-state.md
> +* **Implementação Mais Simples:** Como o React não depende de mutação, ele não precisa fazer nada de especial com seus objetos. Ele não precisa sequestrar suas propriedades, sempre envolvê-las em Pro
uma tradução mais correta de --without additional performance or correctness pitfalls. é:

--sem problemas adicionais de desempenho ou correção

2023-05-29 16:35 UTC, dieguesmosken commented on src/content/learn/updating-objects-in-state.md
> +#### Atualize um objeto com Immerr {/*update-an-object-with-immer*/}
Immer com um r só exatamente igual ao inglês

2023-05-30 15:18 UTC, Egpereira commented on src/content/learn/updating-objects-in-state.md
> +#### Atualize um objeto com Immerr {/*update-an-object-with-immer*/}
Corrigido!

2023-05-30 22:09 UTC, dieguesmosken approved these changes
a tradução está coesa, sem erros

2023-05-31 14:20 UTC, merged