Translates `responding-to-events` page
reactjs/pt-br.react.dev pull request #684
Opened 2023-05-07 13:24 UTC by alexandredev3

Tradução da pagina `Responding to Events`

obs:
- Traduzir `analytics` para `coleta de dados`, não sei se essa é a melhor tradução ou se poderia deixar apenas `analytics` mesmo, o que acham?

2023-05-13 23:13 UTC, natrodrigo requested changes
Olá @alexandredev3 , parabéns pela tradução, está ótima!
Deixei alguns comentários para sua análise. Muito obrigado!

2023-05-13 23:13 UTC, natrodrigo commented on src/content/learn/responding-to-events.md
> +Isso permite que esses dois botões exibem mensagens diferentes. Tente alterar as mensagens passadas para eles.
```suggestion
Isso permite que esses dois botões exibam mensagens diferentes. Tente alterar as mensagens passadas para eles.
```

2023-05-13 23:13 UTC, natrodrigo commented on src/content/learn/responding-to-events.md
> +É comum que o componente pai especifique o manipulador de eventos de um componente filho. Por exemplo, considere os botões: dependendo do contexto em que o componente `Button` é usado, pode ser neces
```suggestion
É comum que o componente pai defina o manipulador de eventos de um componente filho. Por exemplo, considere os botões: dependendo do contexto em que o componente `Button` é usado, pode ser necessário executar funções diferentes, talvez um reproduza um filme e outro faça o upload de uma imagem.
```

2023-05-13 23:13 UTC, natrodrigo commented on src/content/learn/responding-to-events.md
> +Por fim, seu componente `Button` aceita uma prop chamada `onClick`. Ele passa essa prop diretamente para a tag `<button>` nativa do navegador usando `onClick={onClick}`. Isso diz ao React para chamar
```suggestion
Por fim, seu componente `Button` aceita uma prop chamada `onClick`. Ele passa essa prop diretamente para o elemento `<button>` nativo do navegador usando `onClick={onClick}`. Isso diz ao React para chamar a função quando o botão for clicado.
```

2023-05-13 23:13 UTC, natrodrigo commented on src/content/learn/responding-to-events.md
> +Por convenção, as props dos manipuladores de eventos devem começar com `on`, seguido por uma letra maiúscula.
```suggestion
Por convenção, as props dos manipuladores de eventos devem começar com o termo `on`, seguido por uma letra maiúscula.
```

2023-05-16 17:46 UTC, TarsiSurdi commented on src/content/learn/responding-to-events.md
> +O React permite você adicionar *manipuladores de eventos* (event handler) ao seu JSX. Os manipuladores de eventos são funções independentes que são acionadas em resposta a interações como clicar com
```suggestion
O React permite que você adicione *manipuladores de evento* a sua JSX. Os manipuladores de eventos funções independentes as quais são acionadas em resposta a interações como cliques, passagem do cursor sobre certo elemento, mudança do foco em campos de formulário, entre outros.
```

2023-05-31 14:19 UTC, jhonmike approved these changes

2023-05-31 14:19 UTC, merged