docs(pt-br): translate option page
reactjs/pt-br.react.dev pull request #687
Opened 2023-05-12 21:46 UTC by veri-mm

Traduz a página `[<option>`](https://react.dev/reference/react-dom/components/option).

Issue para referência #555

2023-05-13 20:32 UTC, NivaldoFarias requested changes
Quase redondinho!! Só alguns ajustes mesmo.

2023-05-13 20:32 UTC, NivaldoFarias commented on src/content/reference/react-dom/components/option.md
> +O [componente `<option>` nativo do navegador](https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/option) permite que você renderize uma opção dentro de uma caixa de seleção [`<select>`](/refer
apontar pras docs traduzidas ao invés das comuns foi genial, não tinha feito essas alterações até agora. [Roubei a ideia.](https://github.com/reactjs/pt-br.react.dev/pull/688/commits/01fa6a1a4bdf6fd2fa37ae619a0e0487fc360ec4)

2023-05-13 20:32 UTC, NivaldoFarias commented on src/content/reference/react-dom/components/option.md
> +`<option>` suporta todas as [props comuns dos elementos.](/reference/react-dom/components/common#props)
esse é um que facilmente passa despercebido, mas depois ao ler, soa bem estranho. Algumas alternativas que uso quando preciso traduzir *supports*: 
- "oferece suporte"
- "possui suporte"
- "permite o uso"
- [etc.](https://www.linguee.com/english-portuguese/translation/support.html) (cabe ao contexto tb)

2023-05-13 20:32 UTC, NivaldoFarias commented on src/content/reference/react-dom/components/option.md
> +Além disso, `<option>` suporta as seguintes props:
Mesmo caso relacionado a tradução de *supports*

2023-05-13 20:32 UTC, NivaldoFarias commented on src/content/reference/react-dom/components/option.md
> +Renderize um `<select>` com uma lista de componentes `<option>` dentro para exibir uma caixa de seleção. Atribua a cada `<option>` um `<value>` representando os dados a serem submetidos com o formulá
`<value>` deveria constar `value`

2023-05-13 20:32 UTC, NivaldoFarias commented on src/content/reference/react-dom/components/option.md
> +* O React não suporta o atributo `selected` em `<option>`. Em vez disso, passe o `value` da opção ao componente pai [`<select defaultValue>`](/reference/react-dom/components/select#providing-an-initi
Mesmo caso relacionado a tradução de supports

2023-05-15 22:20 UTC, veri-mm commented
@NivaldoFarias obrigada pela review!

2023-05-17 12:35 UTC, NivaldoFarias approved these changes

2023-05-17 12:35 UTC, NivaldoFarias approved these changes

2023-05-22 12:47 UTC, jhonmike approved these changes

2026-06-16 02:08 UTC, jhonmike commented
Olá @veri-mm, muito obrigado pela contribuição! 🙏

Esta página já foi traduzida e mergeada em #1022, então vou fechar este PR para manter o backlog organizado.

Sua ajuda é muito bem-vinda — se quiser pegar uma página que ainda está pendente, a issue #555 mantém a lista atualizada do que falta traduzir. Valeu! 🚀

2026-06-16 02:08 UTC, closed without merging