Tradução de Conteúdo opcional: Warnings
reactjs/pt-br.react.dev pull request #767
Opened 2024-06-26 05:08 UTC by pecraveiro

Olá! Estou enviando um PR de toda a tradução de conteúdo opcional: Warnings.

2024-06-27 01:51 UTC, rick-ssa requested changes
Parabéns!!! Um belo trabalho foi feito aqui!
Fiz algumas poucas sugestões de alterações.

2024-06-27 15:07 UTC, rick-ssa approved these changes
Tradução feita!

2024-06-28 03:49 UTC, pecraveiro commented
Obrigado @rick-ssa, da nossa parte falta alguma coisa ou só precisamos aguardar mais uma pessoa revisar o PR?

2024-06-28 10:50 UTC, rick-ssa commented
> Obrigado @rick-ssa, da nossa parte falta alguma coisa ou só precisamos aguardar mais uma pessoa revisar o PR?

Acredito que temos que aguardar agora

2024-06-29 13:44 UTC, Zapotoczn requested changes
Marquei umas sugestões para alteração de umas certas palavras para um bom entendimento, no caso da palavra "props" e a "deprecation", acredito que será de bom agregamento estes comentarios.

Sou junior e novo por aqui, caso sejam comentarios inuteis ou algo sem valia por favor me informe pois estou aprendendo junto com vocês.

2024-06-29 13:44 UTC, Zapotoczn commented on src/content/warnings/react-dom-test-utils.md
> +title: Avisos de Depreciação do react-dom/test-utils
Aqui e no proximo arquivo nós temos duas traduçoes diferentes, uma para depreciação e no arquivo "REACT-TEST-RENDERER" voce marcou como descontinuação, será que manter um padrão nas duas seria melhor?

A tradução da frase "Deprecation Warnings" para o português é "Avisos de Obsolescência" ou "Avisos de Depreciação" acho que uma das duas para os dois poderiam ser o mesmo.

2024-06-29 13:44 UTC, Zapotoczn commented on src/content/warnings/react-test-renderer.md
> +title: Avisos de Descontinuação do react-test-renderer
Aqui e no proximo arquivo nós temos duas traduçoes diferentes, uma para depreciação e no arquivo "REACT-TEST-UTILS" voce marcou como depreciação, será que manter um padrão nas duas seria melhor?

A tradução da frase "Deprecation Warnings" para o português é "Avisos de Obsolescência" ou "Avisos de Depreciação" acho que uma das duas para os dois poderiam ser o mesmo

2024-06-29 13:44 UTC, Zapotoczn commented on src/content/warnings/unknown-prop.md
> +1. Você está usando `{...props}` ou `cloneElement(element, props)`? Ao copiar props para um componente filho, você deve garantir que não está acidentalmente encaminhando props que foram destinadas ap
Na linha 5 voce traduziu diretamente a palavra "prop" para propriedade, será que aqui tambem seria interessante passar a palavra "props" para propriedades?

2024-06-29 13:44 UTC, Zapotoczn commented on src/content/warnings/unknown-prop.md
> +Se você receber esse aviso porque está passando props como `{...props}`, seu componente pai precisa "consumir" qualquer prop que seja destinada ao componente pai e não destinada ao componente filho.
mesma questão da tradução da palavra "props"

2024-06-29 13:44 UTC, Zapotoczn commented on src/content/warnings/unknown-prop.md
> +**Ruim:** A prop `layout` inesperada é encaminhada para a tag `div`.
aqui tambem.

2024-06-29 15:24 UTC, pecraveiro commented on src/content/warnings/react-test-renderer.md
> +title: Avisos de Descontinuação do react-test-renderer
https://github.com/reactjs/pt-br.react.dev/pull/767/commits/b08f0e2411094149340e4d9a652f8316855d578b

2024-06-29 15:24 UTC, pecraveiro commented on src/content/warnings/unknown-prop.md
> +1. Você está usando `{...props}` ou `cloneElement(element, props)`? Ao copiar props para um componente filho, você deve garantir que não está acidentalmente encaminhando props que foram destinadas ap
https://github.com/reactjs/pt-br.react.dev/pull/767/commits/b08f0e2411094149340e4d9a652f8316855d578b

2024-06-29 15:25 UTC, pecraveiro commented on src/content/warnings/react-dom-test-utils.md
> +title: Avisos de Depreciação do react-dom/test-utils
https://github.com/reactjs/pt-br.react.dev/pull/767/commits/b08f0e2411094149340e4d9a652f8316855d578b

2024-06-29 15:25 UTC, pecraveiro commented on src/content/warnings/react-dom-test-utils.md
> +title: Avisos de Depreciação do react-dom/test-utils
Obrigado pela revisão!

2024-06-29 17:05 UTC, Zapotoczn commented
Aprovado!

2024-06-29 17:06 UTC, Zapotoczn approved these changes

2024-07-01 05:38 UTC, pecraveiro commented
@eduardomoroni Up

2024-08-09 02:42 UTC, jgb27 approved these changes
Parabéns. Continue assim. Já, já vamos terminar toda documentação.

2024-08-09 15:19 UTC, vinicius77 approved these changes
Looks good to me ! 🎉

2024-09-26 06:29 UTC, pecraveiro commented
@eduardomoroni Up

2024-11-01 12:42 UTC, jhonmike approved these changes
The translation was great, I just commented one link from the Mozilla documentation because it is very good in Portuguese too and this will help the Brazilian reader.

2024-11-01 12:42 UTC, jhonmike commented on src/content/warnings/unknown-prop.md
> +2. Você está usando um atributo DOM não padrão em um nó DOM nativo, talvez para representar dados personalizados. Se você está tentando anexar dados personalizados a um elemento DOM padrão, considere
```suggestion
2. Você está usando um atributo DOM não padrão em um nó DOM nativo, talvez para representar dados personalizados. Se você está tentando anexar dados personalizados a um elemento DOM padrão, considere usar um atributo de dados personalizado conforme descrito [no MDN](https://developer.mozilla.org/pt-BR/docs/Web/Guide/HTML/Using_data_attributes).
```

2024-11-04 12:49 UTC, jhonmike commented
Não entendi o motivo de fechar o PR @pecraveiro, vou enviar o código porque ele esta correto e arrumo o link em um PR futuro!!

2024-11-04 12:50 UTC, merged