Translate forwardRef
reactjs/pt-br.react.dev pull request #773
Opened 2024-08-09 02:37 UTC by jgb27

Realizada a tradução da página forwardRef

issue https://github.com/reactjs/pt-br.react.dev/issues/555

2024-09-11 15:21 UTC, bdsqqq requested changes
Trabalho fenomenal, a tradução ficou ótima.

Apontei algumas perguntas e algumas mudanças necessárias, em maioria relacionadas a consistência ao longo da página.

Novamente, ótimo trabalho, animado pra ver a versão revisada dessa página!

2024-11-01 12:49 UTC, jhonmike commented on src/content/reference/react/forwardRef.md
> +Este componente `Form` [passa uma ref](/reference/react/useRef#manipulating-the-dom-with-a-ref) para `MyInput`. O componente `MyInput` encaminha essa `ref` para a tag `<input>` do navegador. Como res
```suggestion
Este componente `Form` [passa uma ref](/reference/react/useRef#manipulating-the-dom-with-a-ref) para `MyInput`. O componente `MyInput` encaminha essa `ref` para a tag `<input>` do navegador. Como resultado, o componente Form pode acessar esse nó DOM `<input>` e chamar [`focus()`](https://developer.mozilla.org/pt-BR/docs/Web/API/HTMLElement/focus) nele.
```

2024-11-01 12:49 UTC, jhonmike commented on src/content/reference/react/forwardRef.md
> +Clicar no botão chamará [`play()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play) e [`pause()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/pause) em um
```suggestion
Clicar no botão chamará [`play()`](https://developer.mozilla.org/pt-BR/docs/Web/API/HTMLMediaElement/play) e [`pause()`](https://developer.mozilla.org/pt-BR/docs/Web/API/HTMLMediaElement/pause) em um nó DOM `<video>`. O componente `App` define uma referência e a passa para o componente `MyVideoPlayer`. O componente `MyVideoPlayer` encaminha essa referência para o nó `<video>` do navegador. Isso permite que o componente `App` reproduza e pause o `<video>`.
```

2026-06-16 02:08 UTC, jhonmike commented
Olá @jgb27, muito obrigado pela contribuição! 🙏

Esta página já foi traduzida e mergeada em #1058, então vou fechar este PR para manter o backlog organizado.

Sua ajuda é muito bem-vinda — se quiser pegar uma página que ainda está pendente, a issue #555 mantém a lista atualizada do que falta traduzir. Valeu! 🚀

2026-06-16 02:08 UTC, closed without merging