docs(pt-br): tradução da referencia useState
reactjs/pt-br.react.dev pull request #782
Opened 2024-09-12 12:49 UTC by bdsqqq

see: #555

2025-03-25 03:23 UTC, lanamesquita commented
@bdsqqq por favor me adicionar como Assignees. Iniciei a revisão.

2025-03-25 14:03 UTC, bdsqqq commented
> @bdsqqq por favor me adicionar como Assignees. Iniciei a revisão.

não tenho permissão para adicionar, acredito que precise ser um mantenedor

2025-03-25 16:55 UTC, lanamesquita commented
> > @bdsqqq por favor me adicionar como Assignees. Iniciei a revisão.
> 
> não tenho permissão para adicionar, acredito que precise ser um mantenedor

Ah, tudo bem. Achei que o autor tinha essa permissão. Vou continuar de qualquer forma. Devo entregar até o fds.

2025-04-13 01:31 UTC, lanamesquita requested changes
Grande parte das correções está na regra do Glossary sobre não traduzir código. Além disso sugeri algumas alterações de string (permitido no Glossary). Tentei deixar alguns trechos mais compreensivos. 

Uma sugestão global é que como tem muitos exemplos com TODO acho interessante alterar para TASK, pois todo é uma palavra em português e a leitura pode confundir.  Não consegui colocar sugestão de código em todas estas partes, pois só tenho permissão de sugestão onde foi alterado. 

Qualquer dúvida, fico à disposição. Sendo esta uma página tão importante, espero que seja tão logo aprovada e publicada.

2025-04-13 01:31 UTC, lanamesquita commented on src/content/reference/react/useState.md
> +Note que se você chamar uma função `set` durante a renderização, ela deve estar dentro de uma condição como `prevCount !== count`, e deve haver uma chamada como `setPrevCount(count)` dentro da condiç
```suggestion
Note que se você chamar uma função `set` durante a renderização, ela deve estar dentro de uma condição como `prevCount !== count`, e deve haver uma chamada como `setPrevCount(count)` dentro da condição. Caso contrário, seu componente renderizaria em um loop até travar. Além disso, você só pode atualizar o state do componente que está *renderizando* desta forma. Chamar a função `set` de *outro* componente durante a renderização é um erro. Por fim, sua chamada `set` deve [atualizar o state sem mutação](#updating-objects-and-arrays-in-state) -- isso não significa que você pode quebrar outras regras das [funções puras.](/learn/keeping-components-pure)
```

2025-04-13 01:31 UTC, lanamesquita commented on src/content/reference/react/useState.md
> +Este padrão pode ser difícil de entender e geralmente é melhor evitá-lo. No entanto, é melhor do que atualizar o state em um efeito. Quando você chama a função `set` durante a renderização, o React r
```suggestion
Este padrão pode ser difícil de entender e geralmente é melhor evitá-lo. No entanto, é melhor do que atualizar o state em um effect. Quando você chama a função `set` durante a renderização, o React irá renderizar esse componente imediatamente após seu componente sair com uma instrução `return`, e antes de renderizar os filhos. Desta forma, os filhos não precisam renderizar duas vezes. O resto da função do seu componente ainda será executado (e o resultado será descartado). Se sua condição estiver abaixo de todas as chamadas de Hook, você pode adicionar um `return;` antecipado para reiniciar a renderização mais cedo.
```

2025-04-13 01:31 UTC, lanamesquita commented on src/content/reference/react/useState.md
> +O React **ignorará sua atualização se o próximo state for igual ao state anterior**, determinado por uma comparação [`Object.is`](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Glo
```suggestion
O React **ignorará sua atualização se o próximo state for igual ao state anterior**, determinado por uma comparação [`Object.is`](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Object/is). Isso geralmente acontece quando você altera um objeto ou um array no state diretamente:
```
```suggestion
O React **irá ignorar sua atualização se o próximo state for igual ao state anterior**, determinado por uma comparação [`Object.is`](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Object/is). Isso geralmente acontece quando você altera um objeto ou um array no state diretamente:
```

2025-04-13 01:31 UTC, lanamesquita commented on src/content/reference/react/useState.md
> +obj.x = 10;  // 🚩 Errado: mutando um objeto existente
```suggestion
obj.x = 10;  // 🚩 Errado: fez mutação em um objeto existente
```

2025-04-13 01:31 UTC, lanamesquita commented on src/content/reference/react/useState.md
> +Você mutou um objeto `obj` existente e o passou de volta para `setObj`, então o React ignorou a atualização. Para corrigir isso, você precisa garantir que sempre está _substituindo_ objetos e arrays
```suggestion
Você alterou um objeto `obj` existente e o passou de volta para `setObj`, então o React ignorou a atualização. Para corrigir isso, você precisa garantir que sempre está _substituindo_ objetos e arrays no state em vez de _realizar uma mutação_:
```

2025-04-13 01:31 UTC, lanamesquita commented on src/content/reference/react/useState.md
> +Por exemplo, esta função atualizadora impura muta um array no state:
```suggestion
Por exemplo, esta função atualizadora impura realiza mutação em um array no state:
```

2025-04-13 01:31 UTC, lanamesquita commented on src/content/reference/react/useState.md
> +  // 🚩 Erro: mutando o state
```suggestion
  // 🚩 Erro: realiza mutação no state
```

2025-04-13 01:31 UTC, lanamesquita commented on src/content/reference/react/useState.md
> +### Estou tentando definir o state para uma função, mas ela é chamada em vez disso {/*im-trying-to-set-state-to-a-function-but-it-gets-called-instead*/}
```suggestion
### Estou tentando definir o state para uma função, mas em vez disso ela é executada {/*im-trying-to-set-state-to-a-function-but-it-gets-called-instead*/}
```

2025-04-13 01:31 UTC, lanamesquita commented on src/content/reference/react/useState.md
> +Porque você está passando uma função, o React assume que `someFunction` é uma [função inicializadora](#avoiding-recreating-the-initial-state), e que `someOtherFunction` é uma [função atualizadora](#u
```suggestion
Porque você está passando uma função, o React assume que `someFunction` é uma [função inicializadora](#avoiding-recreating-the-initial-state), e que `someOtherFunction` é uma [função atualizadora](#updating-state-based-on-the-previous-state), então tenta chamá-las e armazena o resultado. Para realmente *armazenar* uma função, você precisa colocar `() =>` antes delas em ambos os casos. Então o React irá armazenar as funções que você passa.
```

2025-04-22 14:16 UTC, lanamesquita commented
@bdsqqq finalizei a revisão. Qualquer dúvida sobre as alterações podemos discutir aqui.

2026-06-16 02:08 UTC, jhonmike commented
Olá @bdsqqq, muito obrigado pela contribuição! 🙏

Esta página já foi traduzida e mergeada em #1068, então vou fechar este PR para manter o backlog organizado.

Sua ajuda é muito bem-vinda — se quiser pegar uma página que ainda está pendente, a issue #555 mantém a lista atualizada do que falta traduzir. Valeu! 🚀

2026-06-16 02:08 UTC, closed without merging